//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.General.Basic {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.General.Basic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 版本公告.
        /// </summary>
        public static string C_VersionNotice {
            get {
                return ResourceManager.GetString("C_VersionNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 不再显示.
        /// </summary>
        public static string C_VersionNoticeHide {
            get {
                return ResourceManager.GetString("C_VersionNoticeHide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 当前处于 Avalonia 重构阶段，暂不新增功能，重心放在性能优化与问题修复。
        ///敬请期待基于 Avalonia 架构的 v3 版本！
        ///bug 报 GitHub Issue 或 SECTL QQ组织群 - 833875216.
        /// </summary>
        public static string C_VersionNoticeText {
            get {
                return ResourceManager.GetString("C_VersionNoticeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法应用“{0}”设置：{1}.
        /// </summary>
        public static string M_DesktopIntegrationFailed {
            get {
                return ResourceManager.GetString("M_DesktopIntegrationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 当前进程未获得 Windows UIAccess 权限，已回退为普通置顶。.
        /// </summary>
        public static string M_UiAccessTopmostFallback {
            get {
                return ResourceManager.GetString("M_UiAccessTopmostFallback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭置顶.
        /// </summary>
        public static string O_MainWindowTopmostMode_None {
            get {
                return ResourceManager.GetString("O_MainWindowTopmostMode_None", resourceCulture);
            }
        }

        public static string O_CrashRecoveryMode_None {
            get {
                return ResourceManager.GetString("O_CrashRecoveryMode_None", resourceCulture);
            }
        }

        public static string O_CrashRecoveryMode_PromptAndRestart {
            get {
                return ResourceManager.GetString("O_CrashRecoveryMode_PromptAndRestart", resourceCulture);
            }
        }

        public static string O_CrashRecoveryMode_PromptThenRestart {
            get {
                return ResourceManager.GetString("O_CrashRecoveryMode_PromptThenRestart", resourceCulture);
            }
        }

        public static string O_CrashRecoveryMode_RestartOnly {
            get {
                return ResourceManager.GetString("O_CrashRecoveryMode_RestartOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string O_MainWindowTopmostMode_Topmost {
            get {
                return ResourceManager.GetString("O_MainWindowTopmostMode_Topmost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UIAccess 置顶.
        /// </summary>
        public static string O_MainWindowTopmostMode_UiAccess {
            get {
                return ResourceManager.GetString("O_MainWindowTopmostMode_UiAccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 行为.
        /// </summary>
        public static string S_Behavior {
            get {
                return ResourceManager.GetString("S_Behavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动保存窗口大小.
        /// </summary>
        public static string S_Behavior_AutoSaveWindowSize {
            get {
                return ResourceManager.GetString("S_Behavior_AutoSaveWindowSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 是否自动保存窗口大小.
        /// </summary>
        public static string S_Behavior_AutoSaveWindowSize_D {
            get {
                return ResourceManager.GetString("S_Behavior_AutoSaveWindowSize_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开机自启.
        /// </summary>
        public static string S_Behavior_Autostart {
            get {
                return ResourceManager.GetString("S_Behavior_Autostart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置软件是否随系统启动自动运行.
        /// </summary>
        public static string S_Behavior_Autostart_D {
            get {
                return ResourceManager.GetString("S_Behavior_Autostart_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 后台驻留.
        /// </summary>
        public static string S_Behavior_BackgroundResident {
            get {
                return ResourceManager.GetString("S_Behavior_BackgroundResident", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭所有窗口后是否仍在后台常驻.
        /// </summary>
        public static string S_Behavior_BackgroundResident_D {
            get {
                return ResourceManager.GetString("S_Behavior_BackgroundResident_D", resourceCulture);
            }
        }

        public static string S_Behavior_CrashRecovery {
            get {
                return ResourceManager.GetString("S_Behavior_CrashRecovery", resourceCulture);
            }
        }

        public static string S_Behavior_CrashRecovery_D {
            get {
                return ResourceManager.GetString("S_Behavior_CrashRecovery_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示语言.
        /// </summary>
        public static string S_Behavior_Language {
            get {
                return ResourceManager.GetString("S_Behavior_Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 切换软件界面语言（重启软件后生效）.
        /// </summary>
        public static string S_Behavior_Language_D {
            get {
                return ResourceManager.GetString("S_Behavior_Language_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 主窗口置顶模式.
        /// </summary>
        public static string S_Behavior_MainWindowTopmostMode {
            get {
                return ResourceManager.GetString("S_Behavior_MainWindowTopmostMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择主窗口置顶方式（UIAccess 置顶需以管理员运行）.
        /// </summary>
        public static string S_Behavior_MainWindowTopmostMode_D {
            get {
                return ResourceManager.GetString("S_Behavior_MainWindowTopmostMode_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择主窗口是否保持在其他窗口上方.
        /// </summary>
        public static string S_Behavior_MainWindowTopmostMode_NonWindows_D {
            get {
                return ResourceManager.GetString("S_Behavior_MainWindowTopmostMode_NonWindows_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启动显示主窗口.
        /// </summary>
        public static string S_Behavior_ShowStartupWindow {
            get {
                return ResourceManager.GetString("S_Behavior_ShowStartupWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置软件启动时是否自动显示主窗口.
        /// </summary>
        public static string S_Behavior_ShowStartupWindow_D {
            get {
                return ResourceManager.GetString("S_Behavior_ShowStartupWindow_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL 协议注册 &amp; IPC 服务.
        /// </summary>
        public static string S_Behavior_UrlProtocol {
            get {
                return ResourceManager.GetString("S_Behavior_UrlProtocol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 注册自定义 URL 协议 (secrandom://)，并启用 IPC 通信，支持链接启动与外部联动.
        /// </summary>
        public static string S_Behavior_UrlProtocol_D {
            get {
                return ResourceManager.GetString("S_Behavior_UrlProtocol_D", resourceCulture);
            }
        }

    }
}
