//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Update {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Update.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 此页面先保留 v2 的设置入口和配置项，后续可接入真实更新检查服务。.
        /// </summary>
        public static string M_UpdateServicePlaceholder_Message {
            get {
                return ResourceManager.GetString("M_UpdateServicePlaceholder_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更新服务尚未接入.
        /// </summary>
        public static string M_UpdateServicePlaceholder_Title {
            get {
                return ResourceManager.GetString("M_UpdateServicePlaceholder_Title", resourceCulture);
            }
        }

        public static string C_CheckUpdates => ResourceManager.GetString("C_CheckUpdates", resourceCulture);

        public static string C_InstallUpdate => ResourceManager.GetString("C_InstallUpdate", resourceCulture);

        public static string C_DownloadAndInstall => ResourceManager.GetString("C_DownloadAndInstall", resourceCulture);

        public static string C_ForceCheckUpdates => ResourceManager.GetString("C_ForceCheckUpdates", resourceCulture);

        public static string C_ForceCheckUpdates_D => ResourceManager.GetString("C_ForceCheckUpdates_D", resourceCulture);

        public static string M_StatusNotChecked => ResourceManager.GetString("M_StatusNotChecked", resourceCulture);

        public static string O_UpdateChannel_Alpha => ResourceManager.GetString("O_UpdateChannel_Alpha", resourceCulture);

        public static string O_UpdateChannel_Beta => ResourceManager.GetString("O_UpdateChannel_Beta", resourceCulture);

        public static string O_UpdateSource_Sectl => ResourceManager.GetString("O_UpdateSource_Sectl", resourceCulture);

        public static string S_Check => ResourceManager.GetString("S_Check", resourceCulture);

        public static string S_Check_D => ResourceManager.GetString("S_Check_D", resourceCulture);

        /// <summary>
        ///   Looks up a localized string similar to 每天.
        /// </summary>
        public static string O_AutoUpdateMode_Daily {
            get {
                return ResourceManager.GetString("O_AutoUpdateMode_Daily", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 手动检查.
        /// </summary>
        public static string O_AutoUpdateMode_Manual {
            get {
                return ResourceManager.GetString("O_AutoUpdateMode_Manual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string O_AutoUpdateMode_Off {
            get {
                return ResourceManager.GetString("O_AutoUpdateMode_Off", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 每周.
        /// </summary>
        public static string O_AutoUpdateMode_Weekly {
            get {
                return ResourceManager.GetString("O_AutoUpdateMode_Weekly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 预览版.
        /// </summary>
        public static string O_UpdateChannel_Preview {
            get {
                return ResourceManager.GetString("O_UpdateChannel_Preview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 稳定版.
        /// </summary>
        public static string O_UpdateChannel_Stable {
            get {
                return ResourceManager.GetString("O_UpdateChannel_Stable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string O_UpdateSource_GitHub {
            get {
                return ResourceManager.GetString("O_UpdateSource_GitHub", resourceCulture);
            }
        }

        public static string O_AutoUpdateMode_Notify => ResourceManager.GetString("O_AutoUpdateMode_Notify", resourceCulture);

        public static string O_AutoUpdateMode_Download => ResourceManager.GetString("O_AutoUpdateMode_Download", resourceCulture);

        public static string O_AutoUpdateMode_Install => ResourceManager.GetString("O_AutoUpdateMode_Install", resourceCulture);

        /// <summary>
        ///   Looks up a localized string similar to GitHub 镜像.
        /// </summary>
        public static string O_UpdateSource_GitHubMirror {
            get {
                return ResourceManager.GetString("O_UpdateSource_GitHubMirror", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 官方镜像.
        /// </summary>
        public static string O_UpdateSource_OfficialMirror {
            get {
                return ResourceManager.GetString("O_UpdateSource_OfficialMirror", resourceCulture);
            }
        }

        public static string O_UpdateSource_Auto => ResourceManager.GetString("O_UpdateSource_Auto", resourceCulture);

        /// <summary>
        ///   Looks up a localized string similar to 更新设置.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更新策略.
        /// </summary>
        public static string S_Strategy {
            get {
                return ResourceManager.GetString("S_Strategy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动更新模式.
        /// </summary>
        public static string S_Strategy_AutoUpdateMode {
            get {
                return ResourceManager.GetString("S_Strategy_AutoUpdateMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控制程序检查与提示更新的频率。.
        /// </summary>
        public static string S_Strategy_AutoUpdateMode_D {
            get {
                return ResourceManager.GetString("S_Strategy_AutoUpdateMode_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更新通道.
        /// </summary>
        public static string S_Strategy_Channel {
            get {
                return ResourceManager.GetString("S_Strategy_Channel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择稳定版或预览版更新。.
        /// </summary>
        public static string S_Strategy_Channel_D {
            get {
                return ResourceManager.GetString("S_Strategy_Channel_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 上次检查时间.
        /// </summary>
        public static string S_Strategy_LastCheckTime {
            get {
                return ResourceManager.GetString("S_Strategy_LastCheckTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示最近一次检查更新的时间。.
        /// </summary>
        public static string S_Strategy_LastCheckTime_D {
            get {
                return ResourceManager.GetString("S_Strategy_LastCheckTime_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更新来源.
        /// </summary>
        public static string S_Strategy_Source {
            get {
                return ResourceManager.GetString("S_Strategy_Source", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择用于检查更新的下载来源。.
        /// </summary>
        public static string S_Strategy_Source_D {
            get {
                return ResourceManager.GetString("S_Strategy_Source_D", resourceCulture);
            }
        }
    }
}
