//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.MainPages.Timer {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SecRandom.Langs.MainPages.Timer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        public static string C_Countdown {
            get {
                return ResourceManager.GetString("C_Countdown", resourceCulture);
            }
        }
        
        public static string C_Stopwatch {
            get {
                return ResourceManager.GetString("C_Stopwatch", resourceCulture);
            }
        }
        
        public static string C_Clock {
            get {
                return ResourceManager.GetString("C_Clock", resourceCulture);
            }
        }
        
        public static string C_Start {
            get {
                return ResourceManager.GetString("C_Start", resourceCulture);
            }
        }
        
        public static string C_Pause {
            get {
                return ResourceManager.GetString("C_Pause", resourceCulture);
            }
        }
        
        public static string C_Reset {
            get {
                return ResourceManager.GetString("C_Reset", resourceCulture);
            }
        }
        
        public static string C_Lap {
            get {
                return ResourceManager.GetString("C_Lap", resourceCulture);
            }
        }
        
        public static string C_ClearLaps {
            get {
                return ResourceManager.GetString("C_ClearLaps", resourceCulture);
            }
        }
        
        public static string C_TotalTime {
            get {
                return ResourceManager.GetString("C_TotalTime", resourceCulture);
            }
        }
        
        public static string C_ShowMilliseconds {
            get {
                return ResourceManager.GetString("C_ShowMilliseconds", resourceCulture);
            }
        }
        
        public static string C_MiniWindow {
            get {
                return ResourceManager.GetString("C_MiniWindow", resourceCulture);
            }
        }
        
        public static string C_Restore {
            get {
                return ResourceManager.GetString("C_Restore", resourceCulture);
            }
        }
        
        public static string C_Presets {
            get {
                return ResourceManager.GetString("C_Presets", resourceCulture);
            }
        }
        
        public static string C_CommonPresets {
            get {
                return ResourceManager.GetString("C_CommonPresets", resourceCulture);
            }
        }
        
        public static string C_RecentPresets {
            get {
                return ResourceManager.GetString("C_RecentPresets", resourceCulture);
            }
        }
        
        public static string M_Ready {
            get {
                return ResourceManager.GetString("M_Ready", resourceCulture);
            }
        }
        
        public static string M_Running {
            get {
                return ResourceManager.GetString("M_Running", resourceCulture);
            }
        }
        
        public static string M_TimeUp {
            get {
                return ResourceManager.GetString("M_TimeUp", resourceCulture);
            }
        }
        
        public static string M_StopwatchDetails {
            get {
                return ResourceManager.GetString("M_StopwatchDetails", resourceCulture);
            }
        }
        
        public static string M_ClockDetails {
            get {
                return ResourceManager.GetString("M_ClockDetails", resourceCulture);
            }
        }
        
        public static string M_NoRecentPresets {
            get {
                return ResourceManager.GetString("M_NoRecentPresets", resourceCulture);
            }
        }
        
        public static string C_Tips {
            get {
                return ResourceManager.GetString("C_Tips", resourceCulture);
            }
        }
    }
}
