//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Core.Langs.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Core.Langs.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiSans (默认).
        /// </summary>
        public static string O_DefaultFontFamily {
            get {
                return ResourceManager.GetString("O_DefaultFontFamily", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 是否在此处启用特定的设置.
        /// </summary>
        public static string C_AttachedSettingsEnableTip {
            get {
                return ResourceManager.GetString("C_AttachedSettingsEnableTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 附加设置.
        /// </summary>
        public static string C_AttachedSettings {
            get {
                return ResourceManager.GetString("C_AttachedSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开附加设置.
        /// </summary>
        public static string C_AttachedSettingsButtonTip {
            get {
                return ResourceManager.GetString("C_AttachedSettingsButtonTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 这里还什么都没有喵～.
        /// </summary>
        public static string M_Nothing {
            get {
                return ResourceManager.GetString("M_Nothing", resourceCulture);
            }
        }
    }
}
