//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.Common {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 一个易用的点名/抽奖软件，专为教育场景设计，让课堂点名更高效透明.
        /// </summary>
        public static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 本项目基于 GNU General Public License v3.0 获得许可。.
        /// </summary>
        public static string App_License {
            get {
                return ResourceManager.GetString("App_License", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 内幕设置.
        /// </summary>
        public static string AttachedSettings_BehindScene {
            get {
                return ResourceManager.GetString("AttachedSettings_BehindScene", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (等待编写).
        /// </summary>
        public static string C_ToBeWritten {
            get {
                return ResourceManager.GetString("C_ToBeWritten", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string Feat_History {
            get {
                return ResourceManager.GetString("Feat_History", resourceCulture);
            }
        }

        public static string Feat_RollCallHistory {
            get {
                return ResourceManager.GetString("Feat_RollCallHistory", resourceCulture);
            }
        }

        public static string Feat_LotteryHistory {
            get {
                return ResourceManager.GetString("Feat_LotteryHistory", resourceCulture);
            }
        }

        public static string Settings_HistoryManagement {
            get {
                return ResourceManager.GetString("Settings_HistoryManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽奖.
        /// </summary>
        public static string Feat_Lottery {
            get {
                return ResourceManager.GetString("Feat_Lottery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 闪抽.
        /// </summary>
        public static string Feat_QuickDraw {
            get {
                return ResourceManager.GetString("Feat_QuickDraw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点名.
        /// </summary>
        public static string Feat_RollCall {
            get {
                return ResourceManager.GetString("Feat_RollCall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Feat_Settings {
            get {
                return ResourceManager.GetString("Feat_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 退出程序.
        /// </summary>
        public static string Menu_ExitProgram {
            get {
                return ResourceManager.GetString("Menu_ExitProgram", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开主窗口.
        /// </summary>
        public static string Menu_OpenMainWindow {
            get {
                return ResourceManager.GetString("Menu_OpenMainWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开设置.
        /// </summary>
        public static string Menu_OpenSettings {
            get {
                return ResourceManager.GetString("Menu_OpenSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 重启程序.
        /// </summary>
        public static string Menu_RestartProgram {
            get {
                return ResourceManager.GetString("Menu_RestartProgram", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关于 SecRandom.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 外观.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份设置.
        /// </summary>
        public static string Settings_Backup {
            get {
                return ResourceManager.GetString("Settings_Backup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 基础.
        /// </summary>
        public static string Settings_Basic {
            get {
                return ResourceManager.GetString("Settings_Basic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取设置.
        /// </summary>
        public static string Settings_Draw {
            get {
                return ResourceManager.GetString("Settings_Draw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 浮窗管理.
        /// </summary>
        public static string Settings_FloatingWindow {
            get {
                return ResourceManager.GetString("Settings_FloatingWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 通用设置.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string Settings_Home {
            get {
                return ResourceManager.GetString("Settings_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 联动设置.
        /// </summary>
        public static string Settings_Linkage {
            get {
                return ResourceManager.GetString("Settings_Linkage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知设置.
        /// </summary>
        public static string Settings_LotteryNotification {
            get {
                return ResourceManager.GetString("Settings_LotteryNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 通知设置.
        /// </summary>
        public static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 个性化设置.
        /// </summary>
        public static string Settings_Personalized {
            get {
                return ResourceManager.GetString("Settings_Personalized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知设置.
        /// </summary>
        public static string Settings_QuickDrawNotification {
            get {
                return ResourceManager.GetString("Settings_QuickDrawNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点名通知设置.
        /// </summary>
        public static string Settings_RollCallNotification {
            get {
                return ResourceManager.GetString("Settings_RollCallNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 名单管理.
        /// </summary>
        public static string Settings_RosterManagement {
            get {
                return ResourceManager.GetString("Settings_RosterManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 安全设置.
        /// </summary>
        public static string Settings_Security {
            get {
                return ResourceManager.GetString("Settings_Security", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更新设置.
        /// </summary>
        public static string Settings_Update {
            get {
                return ResourceManager.GetString("Settings_Update", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音设置.
        /// </summary>
        public static string Settings_Voice {
            get {
                return ResourceManager.GetString("Settings_Voice", resourceCulture);
            }
        }

        public static string Settings_DefaultNotification {
            get {
                return ResourceManager.GetString("Settings_DefaultNotification", resourceCulture);
            }
        }

        public static string Settings_EnableShortcut {
            get {
                return ResourceManager.GetString("Settings_EnableShortcut", resourceCulture);
            }
        }

        public static string Settings_EnableShortcut_D {
            get {
                return ResourceManager.GetString("Settings_EnableShortcut_D", resourceCulture);
            }
        }

        public static string Settings_FairPick {
            get {
                return ResourceManager.GetString("Settings_FairPick", resourceCulture);
            }
        }

        public static string Settings_FairPick_BaseWeight {
            get {
                return ResourceManager.GetString("Settings_FairPick_BaseWeight", resourceCulture);
            }
        }

        public static string Settings_FairPick_BaseWeight_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_BaseWeight_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_ByGender {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByGender", resourceCulture);
            }
        }

        public static string Settings_FairPick_ByGender_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByGender_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_ByGroup {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByGroup", resourceCulture);
            }
        }

        public static string Settings_FairPick_ByGroup_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByGroup_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_ByTime {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByTime", resourceCulture);
            }
        }

        public static string Settings_FairPick_ByTime_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByTime_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_ByTotal {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByTotal", resourceCulture);
            }
        }

        public static string Settings_FairPick_ByTotal_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByTotal_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_FrequencyWeight {
            get {
                return ResourceManager.GetString("Settings_FairPick_FrequencyWeight", resourceCulture);
            }
        }

        public static string Settings_FairPick_FrequencyWeight_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_FrequencyWeight_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_GapProtection {
            get {
                return ResourceManager.GetString("Settings_FairPick_GapProtection", resourceCulture);
            }
        }

        public static string Settings_FairPick_GapProtection_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_GapProtection_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_GapThreshold {
            get {
                return ResourceManager.GetString("Settings_FairPick_GapThreshold", resourceCulture);
            }
        }

        public static string Settings_FairPick_GapThreshold_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_GapThreshold_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_MinMaxWeight {
            get {
                return ResourceManager.GetString("Settings_FairPick_MinMaxWeight", resourceCulture);
            }
        }

        public static string Settings_FairPick_MinMaxWeight_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_MinMaxWeight_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_Protection {
            get {
                return ResourceManager.GetString("Settings_FairPick_Protection", resourceCulture);
            }
        }

        public static string Settings_FairPick_Shield {
            get {
                return ResourceManager.GetString("Settings_FairPick_Shield", resourceCulture);
            }
        }

        public static string Settings_FairPick_Shield_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_Shield_D", resourceCulture);
            }
        }

        public static string Settings_FairPick_Weights {
            get {
                return ResourceManager.GetString("Settings_FairPick_Weights", resourceCulture);
            }
        }

        public static string Settings_Music {
            get {
                return ResourceManager.GetString("Settings_Music", resourceCulture);
            }
        }

        public static string Settings_OpenLotteryPageShortcut {
            get {
                return ResourceManager.GetString("Settings_OpenLotteryPageShortcut", resourceCulture);
            }
        }

        public static string Settings_OpenLotteryPageShortcut_D {
            get {
                return ResourceManager.GetString("Settings_OpenLotteryPageShortcut_D", resourceCulture);
            }
        }

        public static string Settings_OpenRollCallPageShortcut {
            get {
                return ResourceManager.GetString("Settings_OpenRollCallPageShortcut", resourceCulture);
            }
        }

        public static string Settings_OpenRollCallPageShortcut_D {
            get {
                return ResourceManager.GetString("Settings_OpenRollCallPageShortcut_D", resourceCulture);
            }
        }

        public static string Settings_Plugin {
            get {
                return ResourceManager.GetString("Settings_Plugin", resourceCulture);
            }
        }

        public static string Settings_QuickDrawShortcut {
            get {
                return ResourceManager.GetString("Settings_QuickDrawShortcut", resourceCulture);
            }
        }

        public static string Settings_QuickDrawShortcut_D {
            get {
                return ResourceManager.GetString("Settings_QuickDrawShortcut_D", resourceCulture);
            }
        }

        public static string Settings_ShortcutExampleLottery {
            get {
                return ResourceManager.GetString("Settings_ShortcutExampleLottery", resourceCulture);
            }
        }

        public static string Settings_ShortcutExampleQuickDraw {
            get {
                return ResourceManager.GetString("Settings_ShortcutExampleQuickDraw", resourceCulture);
            }
        }

        public static string Settings_ShortcutExampleRollCall {
            get {
                return ResourceManager.GetString("Settings_ShortcutExampleRollCall", resourceCulture);
            }
        }

        public static string Settings_VoiceMusic {
            get {
                return ResourceManager.GetString("Settings_VoiceMusic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 频率函数.
        /// </summary>
        public static string Settings_FairPick_FrequencyFunction {
            get {
                return ResourceManager.GetString("Settings_FairPick_FrequencyFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择历史抽取次数如何影响候选权重.
        /// </summary>
        public static string Settings_FairPick_FrequencyFunction_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_FrequencyFunction_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 线性.
        /// </summary>
        public static string Settings_FairPick_FrequencyFunction_Linear {
            get {
                return ResourceManager.GetString("Settings_FairPick_FrequencyFunction_Linear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 平方根.
        /// </summary>
        public static string Settings_FairPick_FrequencyFunction_SquareRoot {
            get {
                return ResourceManager.GetString("Settings_FairPick_FrequencyFunction_SquareRoot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 指数.
        /// </summary>
        public static string Settings_FairPick_FrequencyFunction_Index {
            get {
                return ResourceManager.GetString("Settings_FairPick_FrequencyFunction_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 小组/性别/时间权重.
        /// </summary>
        public static string Settings_FairPick_GroupGenderTimeWeight {
            get {
                return ResourceManager.GetString("Settings_FairPick_GroupGenderTimeWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 依次设置小组平衡、性别平衡和时间因素在总权重中的占比.
        /// </summary>
        public static string Settings_FairPick_GroupGenderTimeWeight_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_GroupGenderTimeWeight_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 最小候选池大小.
        /// </summary>
        public static string Settings_FairPick_MinPoolSize {
            get {
                return ResourceManager.GetString("Settings_FairPick_MinPoolSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 候选数量低于该值时减少保护策略对抽取池的影响.
        /// </summary>
        public static string Settings_FairPick_MinPoolSize_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_MinPoolSize_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 冷启动保护.
        /// </summary>
        public static string Settings_FairPick_ColdStart {
            get {
                return ResourceManager.GetString("Settings_FairPick_ColdStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在历史记录较少时降低频率权重带来的突变.
        /// </summary>
        public static string Settings_FairPick_ColdStart_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_ColdStart_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 冷启动轮数.
        /// </summary>
        public static string Settings_FairPick_ColdStartRounds {
            get {
                return ResourceManager.GetString("Settings_FairPick_ColdStartRounds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 总抽取次数达到该值前应用冷启动保护.
        /// </summary>
        public static string Settings_FairPick_ColdStartRounds_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_ColdStartRounds_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 屏蔽时间.
        /// </summary>
        public static string Settings_FairPick_ShieldTime {
            get {
                return ResourceManager.GetString("Settings_FairPick_ShieldTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽中后在指定时间范围内降低再次被抽中的权重.
        /// </summary>
        public static string Settings_FairPick_ShieldTime_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_ShieldTime_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        public static string Settings_FairPick_ShieldTimeUnit_Seconds {
            get {
                return ResourceManager.GetString("Settings_FairPick_ShieldTimeUnit_Seconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 分钟.
        /// </summary>
        public static string Settings_FairPick_ShieldTimeUnit_Minutes {
            get {
                return ResourceManager.GetString("Settings_FairPick_ShieldTimeUnit_Minutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 小时.
        /// </summary>
        public static string Settings_FairPick_ShieldTimeUnit_Hours {
            get {
                return ResourceManager.GetString("Settings_FairPick_ShieldTimeUnit_Hours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 应用程序已在运行.
        /// </summary>
        public static string MultiInstance_Title {
            get {
                return ResourceManager.GetString("MultiInstance_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecRandom 已经有一个实例正在运行。.
        /// </summary>
        public static string MultiInstance_Message {
            get {
                return ResourceManager.GetString("MultiInstance_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开已有实例主界面.
        /// </summary>
        public static string MultiInstance_OpenExisting {
            get {
                return ResourceManager.GetString("MultiInstance_OpenExisting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 重启实例.
        /// </summary>
        public static string MultiInstance_Restart {
            get {
                return ResourceManager.GetString("MultiInstance_Restart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string MultiInstance_Cancel {
            get {
                return ResourceManager.GetString("MultiInstance_Cancel", resourceCulture);
            }
        }
    }
}
