//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Home {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Home.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string C_ListCount => ResourceManager.GetString("C_ListCount", resourceCulture);
        public static string C_LastDrawn => ResourceManager.GetString("C_LastDrawn", resourceCulture);
        public static string C_HistorySummary => ResourceManager.GetString("C_HistorySummary", resourceCulture);
        public static string C_Lottery => ResourceManager.GetString("C_Lottery", resourceCulture);
        public static string C_Name => ResourceManager.GetString("C_Name", resourceCulture);
        public static string C_PoolCount => ResourceManager.GetString("C_PoolCount", resourceCulture);
        public static string C_PrizeCount => ResourceManager.GetString("C_PrizeCount", resourceCulture);
        public static string C_RollCall => ResourceManager.GetString("C_RollCall", resourceCulture);
        public static string C_StudentCount => ResourceManager.GetString("C_StudentCount", resourceCulture);
        public static string C_TotalDrawnCount => ResourceManager.GetString("C_TotalDrawnCount", resourceCulture);
        public static string C_TotalRounds => ResourceManager.GetString("C_TotalRounds", resourceCulture);
        public static string M_NoLotteryPools => ResourceManager.GetString("M_NoLotteryPools", resourceCulture);
        public static string M_NoRollCallLists => ResourceManager.GetString("M_NoRollCallLists", resourceCulture);
        public static string M_NoDrawHistory => ResourceManager.GetString("M_NoDrawHistory", resourceCulture);
        public static string M_JustNow => ResourceManager.GetString("M_JustNow", resourceCulture);
        public static string M_MinutesAgo => ResourceManager.GetString("M_MinutesAgo", resourceCulture);
        public static string M_TodayAt => ResourceManager.GetString("M_TodayAt", resourceCulture);
        public static string M_YesterdayAt => ResourceManager.GetString("M_YesterdayAt", resourceCulture);
        public static string Page_Description => ResourceManager.GetString("Page_Description", resourceCulture);
        public static string Page_Title => ResourceManager.GetString("Page_Title", resourceCulture);
        public static string S_Overview => ResourceManager.GetString("S_Overview", resourceCulture);
        public static string S_Overview_D => ResourceManager.GetString("S_Overview_D", resourceCulture);
    }
}
