//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Notification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Notification.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同时使用.
        /// </summary>
        public static string O_NotificationService_Both {
            get {
                return ResourceManager.GetString("O_NotificationService_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIsland.
        /// </summary>
        public static string O_NotificationService_ClassIsland {
            get {
                return ResourceManager.GetString("O_NotificationService_ClassIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecRandom 内置通知.
        /// </summary>
        public static string O_NotificationService_SecRandom {
            get {
                return ResourceManager.GetString("O_NotificationService_SecRandom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 不指定.
        /// </summary>
        public static string O_Monitor_Unspecified {
            get {
                return ResourceManager.GetString("O_Monitor_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底部.
        /// </summary>
        public static string O_WindowPosition_Bottom {
            get {
                return ResourceManager.GetString("O_WindowPosition_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左下.
        /// </summary>
        public static string O_WindowPosition_BottomLeft {
            get {
                return ResourceManager.GetString("O_WindowPosition_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右下.
        /// </summary>
        public static string O_WindowPosition_BottomRight {
            get {
                return ResourceManager.GetString("O_WindowPosition_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中心.
        /// </summary>
        public static string O_WindowPosition_Center {
            get {
                return ResourceManager.GetString("O_WindowPosition_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左侧.
        /// </summary>
        public static string O_WindowPosition_Left {
            get {
                return ResourceManager.GetString("O_WindowPosition_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右侧.
        /// </summary>
        public static string O_WindowPosition_Right {
            get {
                return ResourceManager.GetString("O_WindowPosition_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部.
        /// </summary>
        public static string O_WindowPosition_Top {
            get {
                return ResourceManager.GetString("O_WindowPosition_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左上.
        /// </summary>
        public static string O_WindowPosition_TopLeft {
            get {
                return ResourceManager.GetString("O_WindowPosition_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右上.
        /// </summary>
        public static string O_WindowPosition_TopRight {
            get {
                return ResourceManager.GetString("O_WindowPosition_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认通知设置.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知显示器.
        /// </summary>
        public static string S_Common_EnabledMonitor {
            get {
                return ResourceManager.GetString("S_Common_EnabledMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定通知窗口显示在哪个显示器；不指定时使用主显示器。.
        /// </summary>
        public static string S_Common_EnabledMonitor_D {
            get {
                return ResourceManager.GetString("S_Common_EnabledMonitor_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内置通知浮窗.
        /// </summary>
        public static string S_Common_FloatingWindow {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗关闭时间.
        /// </summary>
        public static string S_Common_FloatingWindowAutoCloseTime {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowAutoCloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内置通知浮窗自动关闭前保留的秒数。.
        /// </summary>
        public static string S_Common_FloatingWindowAutoCloseTime_D {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowAutoCloseTime_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗显示器.
        /// </summary>
        public static string S_Common_FloatingWindowEnabledMonitor {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowEnabledMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定内置通知浮窗显示在哪个显示器；不指定时使用主显示器。.
        /// </summary>
        public static string S_Common_FloatingWindowEnabledMonitor_D {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowEnabledMonitor_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗偏移.
        /// </summary>
        public static string S_Common_FloatingWindowOffset {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置内置通知浮窗相对默认位置的水平和垂直偏移。.
        /// </summary>
        public static string S_Common_FloatingWindowOffset_D {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowOffset_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗位置.
        /// </summary>
        public static string S_Common_FloatingWindowPosition {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择内置通知浮窗的显示位置。.
        /// </summary>
        public static string S_Common_FloatingWindowPosition_D {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowPosition_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗不透明度.
        /// </summary>
        public static string S_Common_FloatingWindowTransparency {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置内置通知浮窗的不透明度。.
        /// </summary>
        public static string S_Common_FloatingWindowTransparency_D {
            get {
                return ResourceManager.GetString("S_Common_FloatingWindowTransparency_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知服务.
        /// </summary>
        public static string S_Common_NotificationService {
            get {
                return ResourceManager.GetString("S_Common_NotificationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知服务类型.
        /// </summary>
        public static string S_Common_NotificationServiceType {
            get {
                return ResourceManager.GetString("S_Common_NotificationServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择使用 SecRandom 内置通知、ClassIsland 通知或同时使用。.
        /// </summary>
        public static string S_Common_NotificationServiceType_D {
            get {
                return ResourceManager.GetString("S_Common_NotificationServiceType_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        public static string S_Common_BasicSettings {
            get {
                return ResourceManager.GetString("S_Common_BasicSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 通知窗口.
        /// </summary>
        public static string S_Common_NotificationWindowSettings {
            get {
                return ResourceManager.GetString("S_Common_NotificationWindowSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用覆盖.
        /// </summary>
        public static string C_EnableOverride {
            get {
                return ResourceManager.GetString("C_EnableOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认提醒设置.
        /// </summary>
        public static string S_Default {
            get {
                return ResourceManager.GetString("S_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知动画.
        /// </summary>
        public static string S_Default_Animation {
            get {
                return ResourceManager.GetString("S_Default_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示通知时播放进入和退出动画。.
        /// </summary>
        public static string S_Default_Animation_D {
            get {
                return ResourceManager.GetString("S_Default_Animation_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知显示时长.
        /// </summary>
        public static string S_Default_DisplayDuration {
            get {
                return ResourceManager.GetString("S_Default_DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置通知服务显示结果的秒数。.
        /// </summary>
        public static string S_Default_DisplayDuration_D {
            get {
                return ResourceManager.GetString("S_Default_DisplayDuration_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用通知.
        /// </summary>
        public static string S_Default_Enabled {
            get {
                return ResourceManager.GetString("S_Default_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取完成后显示通知结果。.
        /// </summary>
        public static string S_Default_Enabled_D {
            get {
                return ResourceManager.GetString("S_Default_Enabled_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知阈值.
        /// </summary>
        public static string S_Default_MainWindowDisplayThreshold {
            get {
                return ResourceManager.GetString("S_Default_MainWindowDisplayThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过此数量后使用主窗口显示结果。.
        /// </summary>
        public static string S_Default_MainWindowDisplayThreshold_D {
            get {
                return ResourceManager.GetString("S_Default_MainWindowDisplayThreshold_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知偏移.
        /// </summary>
        public static string S_Default_Offset {
            get {
                return ResourceManager.GetString("S_Default_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置通知浮窗相对默认位置的水平和垂直偏移。.
        /// </summary>
        public static string S_Default_Offset_D {
            get {
                return ResourceManager.GetString("S_Default_Offset_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知不透明度.
        /// </summary>
        public static string S_Default_Transparency {
            get {
                return ResourceManager.GetString("S_Default_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置通知浮窗的不透明度。.
        /// </summary>
        public static string S_Default_Transparency_D {
            get {
                return ResourceManager.GetString("S_Default_Transparency_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过阈值时使用主窗口.
        /// </summary>
        public static string S_Default_UseMainWindowWhenExceedThreshold {
            get {
                return ResourceManager.GetString("S_Default_UseMainWindowWhenExceedThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取数量超过阈值时不显示浮窗通知，仅在主窗口显示结果。.
        /// </summary>
        public static string S_Default_UseMainWindowWhenExceedThreshold_D {
            get {
                return ResourceManager.GetString("S_Default_UseMainWindowWhenExceedThreshold_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知位置.
        /// </summary>
        public static string S_Default_WindowPosition {
            get {
                return ResourceManager.GetString("S_Default_WindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择通知浮窗显示位置。.
        /// </summary>
        public static string S_Default_WindowPosition_D {
            get {
                return ResourceManager.GetString("S_Default_WindowPosition_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知.
        /// </summary>
        public static string S_Lottery {
            get {
                return ResourceManager.GetString("S_Lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知动画.
        /// </summary>
        public static string S_Lottery_Animation {
            get {
                return ResourceManager.GetString("S_Lottery_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示抽奖通知时播放进入和退出动画。.
        /// </summary>
        public static string S_Lottery_Animation_D {
            get {
                return ResourceManager.GetString("S_Lottery_Animation_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知显示时长.
        /// </summary>
        public static string S_Lottery_DisplayDuration {
            get {
                return ResourceManager.GetString("S_Lottery_DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置通知服务显示抽奖结果的秒数。.
        /// </summary>
        public static string S_Lottery_DisplayDuration_D {
            get {
                return ResourceManager.GetString("S_Lottery_DisplayDuration_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用抽奖通知.
        /// </summary>
        public static string S_Lottery_Enabled {
            get {
                return ResourceManager.GetString("S_Lottery_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖完成后显示通知结果。.
        /// </summary>
        public static string S_Lottery_Enabled_D {
            get {
                return ResourceManager.GetString("S_Lottery_Enabled_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知阈值.
        /// </summary>
        public static string S_Lottery_MainWindowDisplayThreshold {
            get {
                return ResourceManager.GetString("S_Lottery_MainWindowDisplayThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过此奖品数后使用主窗口显示结果。.
        /// </summary>
        public static string S_Lottery_MainWindowDisplayThreshold_D {
            get {
                return ResourceManager.GetString("S_Lottery_MainWindowDisplayThreshold_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知偏移.
        /// </summary>
        public static string S_Lottery_Offset {
            get {
                return ResourceManager.GetString("S_Lottery_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽奖通知浮窗相对默认位置的水平和垂直偏移。.
        /// </summary>
        public static string S_Lottery_Offset_D {
            get {
                return ResourceManager.GetString("S_Lottery_Offset_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知不透明度.
        /// </summary>
        public static string S_Lottery_Transparency {
            get {
                return ResourceManager.GetString("S_Lottery_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽奖通知浮窗的不透明度。.
        /// </summary>
        public static string S_Lottery_Transparency_D {
            get {
                return ResourceManager.GetString("S_Lottery_Transparency_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过阈值时使用主窗口.
        /// </summary>
        public static string S_Lottery_UseMainWindowWhenExceedThreshold {
            get {
                return ResourceManager.GetString("S_Lottery_UseMainWindowWhenExceedThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取奖品数超过阈值时不显示浮窗通知，仅在主窗口显示结果。.
        /// </summary>
        public static string S_Lottery_UseMainWindowWhenExceedThreshold_D {
            get {
                return ResourceManager.GetString("S_Lottery_UseMainWindowWhenExceedThreshold_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知位置.
        /// </summary>
        public static string S_Lottery_WindowPosition {
            get {
                return ResourceManager.GetString("S_Lottery_WindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择抽奖通知浮窗显示位置。.
        /// </summary>
        public static string S_Lottery_WindowPosition_D {
            get {
                return ResourceManager.GetString("S_Lottery_WindowPosition_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知.
        /// </summary>
        public static string S_QuickDraw {
            get {
                return ResourceManager.GetString("S_QuickDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知动画.
        /// </summary>
        public static string S_QuickDraw_Animation {
            get {
                return ResourceManager.GetString("S_QuickDraw_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示闪抽通知时播放进入和退出动画。.
        /// </summary>
        public static string S_QuickDraw_Animation_D {
            get {
                return ResourceManager.GetString("S_QuickDraw_Animation_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知显示时长.
        /// </summary>
        public static string S_QuickDraw_DisplayDuration {
            get {
                return ResourceManager.GetString("S_QuickDraw_DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置通知服务显示闪抽结果的秒数。.
        /// </summary>
        public static string S_QuickDraw_DisplayDuration_D {
            get {
                return ResourceManager.GetString("S_QuickDraw_DisplayDuration_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用闪抽通知.
        /// </summary>
        public static string S_QuickDraw_Enabled {
            get {
                return ResourceManager.GetString("S_QuickDraw_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速抽取完成后显示通知结果。.
        /// </summary>
        public static string S_QuickDraw_Enabled_D {
            get {
                return ResourceManager.GetString("S_QuickDraw_Enabled_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知阈值.
        /// </summary>
        public static string S_QuickDraw_MainWindowDisplayThreshold {
            get {
                return ResourceManager.GetString("S_QuickDraw_MainWindowDisplayThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过此人数后使用主窗口显示结果。.
        /// </summary>
        public static string S_QuickDraw_MainWindowDisplayThreshold_D {
            get {
                return ResourceManager.GetString("S_QuickDraw_MainWindowDisplayThreshold_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知偏移.
        /// </summary>
        public static string S_QuickDraw_Offset {
            get {
                return ResourceManager.GetString("S_QuickDraw_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置闪抽通知浮窗相对默认位置的水平和垂直偏移。.
        /// </summary>
        public static string S_QuickDraw_Offset_D {
            get {
                return ResourceManager.GetString("S_QuickDraw_Offset_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知不透明度.
        /// </summary>
        public static string S_QuickDraw_Transparency {
            get {
                return ResourceManager.GetString("S_QuickDraw_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置闪抽通知浮窗的不透明度。.
        /// </summary>
        public static string S_QuickDraw_Transparency_D {
            get {
                return ResourceManager.GetString("S_QuickDraw_Transparency_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过阈值时使用主窗口.
        /// </summary>
        public static string S_QuickDraw_UseMainWindowWhenExceedThreshold {
            get {
                return ResourceManager.GetString("S_QuickDraw_UseMainWindowWhenExceedThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取人数超过阈值时不显示浮窗通知，仅在主窗口显示结果。.
        /// </summary>
        public static string S_QuickDraw_UseMainWindowWhenExceedThreshold_D {
            get {
                return ResourceManager.GetString("S_QuickDraw_UseMainWindowWhenExceedThreshold_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知位置.
        /// </summary>
        public static string S_QuickDraw_WindowPosition {
            get {
                return ResourceManager.GetString("S_QuickDraw_WindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择闪抽通知浮窗显示位置。.
        /// </summary>
        public static string S_QuickDraw_WindowPosition_D {
            get {
                return ResourceManager.GetString("S_QuickDraw_WindowPosition_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知.
        /// </summary>
        public static string S_RollCall {
            get {
                return ResourceManager.GetString("S_RollCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知动画.
        /// </summary>
        public static string S_RollCall_Animation {
            get {
                return ResourceManager.GetString("S_RollCall_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示通知时播放进入和退出动画。.
        /// </summary>
        public static string S_RollCall_Animation_D {
            get {
                return ResourceManager.GetString("S_RollCall_Animation_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知显示时长.
        /// </summary>
        public static string S_RollCall_DisplayDuration {
            get {
                return ResourceManager.GetString("S_RollCall_DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置通知服务显示点名结果的秒数。.
        /// </summary>
        public static string S_RollCall_DisplayDuration_D {
            get {
                return ResourceManager.GetString("S_RollCall_DisplayDuration_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用点名通知.
        /// </summary>
        public static string S_RollCall_Enabled {
            get {
                return ResourceManager.GetString("S_RollCall_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名完成后显示通知结果。.
        /// </summary>
        public static string S_RollCall_Enabled_D {
            get {
                return ResourceManager.GetString("S_RollCall_Enabled_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知阈值.
        /// </summary>
        public static string S_RollCall_MainWindowDisplayThreshold {
            get {
                return ResourceManager.GetString("S_RollCall_MainWindowDisplayThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过此人数后使用主窗口显示结果。.
        /// </summary>
        public static string S_RollCall_MainWindowDisplayThreshold_D {
            get {
                return ResourceManager.GetString("S_RollCall_MainWindowDisplayThreshold_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知偏移.
        /// </summary>
        public static string S_RollCall_Offset {
            get {
                return ResourceManager.GetString("S_RollCall_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置点名通知浮窗相对默认位置的水平和垂直偏移。.
        /// </summary>
        public static string S_RollCall_Offset_D {
            get {
                return ResourceManager.GetString("S_RollCall_Offset_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知不透明度.
        /// </summary>
        public static string S_RollCall_Transparency {
            get {
                return ResourceManager.GetString("S_RollCall_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置点名通知浮窗的不透明度。.
        /// </summary>
        public static string S_RollCall_Transparency_D {
            get {
                return ResourceManager.GetString("S_RollCall_Transparency_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过阈值时使用主窗口.
        /// </summary>
        public static string S_RollCall_UseMainWindowWhenExceedThreshold {
            get {
                return ResourceManager.GetString("S_RollCall_UseMainWindowWhenExceedThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取人数超过阈值时不显示浮窗通知，仅在主窗口显示结果。.
        /// </summary>
        public static string S_RollCall_UseMainWindowWhenExceedThreshold_D {
            get {
                return ResourceManager.GetString("S_RollCall_UseMainWindowWhenExceedThreshold_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知位置.
        /// </summary>
        public static string S_RollCall_WindowPosition {
            get {
                return ResourceManager.GetString("S_RollCall_WindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择点名通知浮窗显示位置。.
        /// </summary>
        public static string S_RollCall_WindowPosition_D {
            get {
                return ResourceManager.GetString("S_RollCall_WindowPosition_D", resourceCulture);
            }
        }
    }
}
