// <auto-generated />
#nullable enable
namespace SecRandom.Langs.SettingsPages.General.Verification;

using System.Globalization;
using System.Resources;

public class Resources
{
    private static readonly ResourceManager ResourceManagerInstance = new(
        "SecRandom.Langs.SettingsPages.General.Verification.Resources", typeof(Resources).Assembly);

    public static CultureInfo? Culture { get; set; }
    private static string Get(string key) => ResourceManagerInstance.GetString(key, Culture) ?? key;
    public static string Page_Title => Get(nameof(Page_Title));
    public static string S_Verification => Get(nameof(S_Verification));
    public static string C_WitnessNoticeTitle => Get(nameof(C_WitnessNoticeTitle));
    public static string M_WitnessModeNotice => Get(nameof(M_WitnessModeNotice));
    public static string S_VerificationMode => Get(nameof(S_VerificationMode));
    public static string S_VerificationMode_D => Get(nameof(S_VerificationMode_D));
    public static string O_VerificationMode_Local => Get(nameof(O_VerificationMode_Local));
    public static string O_VerificationMode_Server => Get(nameof(O_VerificationMode_Server));
    public static string C_ModeConfirmTitle => Get(nameof(C_ModeConfirmTitle));
    public static string C_ModeConfirmSwitch => Get(nameof(C_ModeConfirmSwitch));
    public static string C_Cancel => Get(nameof(C_Cancel));
    public static string C_ModeReadConfirm => Get(nameof(C_ModeReadConfirm));
    public static string M_ModeConfirmLocal => Get(nameof(M_ModeConfirmLocal));
    public static string M_ModeConfirmFormal => Get(nameof(M_ModeConfirmFormal));
    public static string S_ProofFolder => Get(nameof(S_ProofFolder));
    public static string S_ProofFolder_D => Get(nameof(S_ProofFolder_D));
    public static string C_OpenProofFolder => Get(nameof(C_OpenProofFolder));
    public static string C_OpenVerificationWebsite => Get(nameof(C_OpenVerificationWebsite));
    public static string S_LocalProofStorageLimit => Get(nameof(S_LocalProofStorageLimit));
    public static string S_LocalProofStorageLimit_D => Get(nameof(S_LocalProofStorageLimit_D));
    public static string O_Storage_16MB => Get(nameof(O_Storage_16MB));
    public static string O_Storage_32MB => Get(nameof(O_Storage_32MB));
    public static string O_Storage_64MB => Get(nameof(O_Storage_64MB));
    public static string O_Storage_128MB => Get(nameof(O_Storage_128MB));
    public static string O_Storage_256MB => Get(nameof(O_Storage_256MB));
    public static string O_Storage_512MB => Get(nameof(O_Storage_512MB));
    public static string O_Storage_1GB => Get(nameof(O_Storage_1GB));
    public static string S_LocalProofRetention => Get(nameof(S_LocalProofRetention));
    public static string S_LocalProofRetention_D => Get(nameof(S_LocalProofRetention_D));
    public static string O_Retention_7 => Get(nameof(O_Retention_7));
    public static string O_Retention_15 => Get(nameof(O_Retention_15));
    public static string O_Retention_30 => Get(nameof(O_Retention_30));
    public static string O_Retention_60 => Get(nameof(O_Retention_60));
    public static string O_Retention_90 => Get(nameof(O_Retention_90));
    public static string O_Retention_Never => Get(nameof(O_Retention_Never));
    public static string C_StatusTitle => Get(nameof(C_StatusTitle));
    public static string M_ServerWitnessedProof => Get(nameof(M_ServerWitnessedProof));
    public static string M_LocalFallbackProof => Get(nameof(M_LocalFallbackProof));
}
