//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Voice {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Voice.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edge TTS.
        /// </summary>
        public static string O_VoiceEngine_EdgeTts {
            get {
                return ResourceManager.GetString("O_VoiceEngine_EdgeTts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统语音.
        /// </summary>
        public static string O_VoiceEngine_System {
            get {
                return ResourceManager.GetString("O_VoiceEngine_System", resourceCulture);
            }
        }

        public static string C_RefreshVoices {
            get {
                return ResourceManager.GetString("C_RefreshVoices", resourceCulture);
            }
        }

        public static string C_TestVoice {
            get {
                return ResourceManager.GetString("C_TestVoice", resourceCulture);
            }
        }

        public static string C_TestVoiceText {
            get {
                return ResourceManager.GetString("C_TestVoiceText", resourceCulture);
            }
        }

        public static string M_TestVoiceCompleted {
            get {
                return ResourceManager.GetString("M_TestVoiceCompleted", resourceCulture);
            }
        }

        public static string M_TestVoiceFailed {
            get {
                return ResourceManager.GetString("M_TestVoiceFailed", resourceCulture);
            }
        }

        public static string M_VoicesRefreshed {
            get {
                return ResourceManager.GetString("M_VoicesRefreshed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音设置.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 播报内容.
        /// </summary>
        public static string S_Content {
            get {
                return ResourceManager.GetString("S_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 播报编号.
        /// </summary>
        public static string S_Content_AnnounceId {
            get {
                return ResourceManager.GetString("S_Content_AnnounceId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 结果中包含编号。.
        /// </summary>
        public static string S_Content_AnnounceId_D {
            get {
                return ResourceManager.GetString("S_Content_AnnounceId_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 播报姓名.
        /// </summary>
        public static string S_Content_AnnounceName {
            get {
                return ResourceManager.GetString("S_Content_AnnounceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 结果中包含姓名。.
        /// </summary>
        public static string S_Content_AnnounceName_D {
            get {
                return ResourceManager.GetString("S_Content_AnnounceName_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音播报.
        /// </summary>
        public static string S_Playback {
            get {
                return ResourceManager.GetString("S_Playback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edge TTS 音色.
        /// </summary>
        public static string S_Playback_EdgeTtsVoice {
            get {
                return ResourceManager.GetString("S_Playback_EdgeTtsVoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edge TTS 使用的 voice 名称。.
        /// </summary>
        public static string S_Playback_EdgeTtsVoice_D {
            get {
                return ResourceManager.GetString("S_Playback_EdgeTtsVoice_D", resourceCulture);
            }
        }

        public static string S_Playback_Actions {
            get {
                return ResourceManager.GetString("S_Playback_Actions", resourceCulture);
            }
        }

        public static string S_Playback_Actions_D {
            get {
                return ResourceManager.GetString("S_Playback_Actions_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用语音播报.
        /// </summary>
        public static string S_Playback_Enable {
            get {
                return ResourceManager.GetString("S_Playback_Enable", resourceCulture);
            }
        }

        public static string S_Playback_Voice {
            get {
                return ResourceManager.GetString("S_Playback_Voice", resourceCulture);
            }
        }

        public static string S_Playback_Voice_D {
            get {
                return ResourceManager.GetString("S_Playback_Voice_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 作为所有抽取语音播报的总开关；各抽取设置可单独控制是否播报。.
        /// </summary>
        public static string S_Playback_Enable_D {
            get {
                return ResourceManager.GetString("S_Playback_Enable_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音引擎.
        /// </summary>
        public static string S_Playback_Engine {
            get {
                return ResourceManager.GetString("S_Playback_Engine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择用于播报的语音引擎。.
        /// </summary>
        public static string S_Playback_Engine_D {
            get {
                return ResourceManager.GetString("S_Playback_Engine_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语速.
        /// </summary>
        public static string S_Playback_SpeechRate {
            get {
                return ResourceManager.GetString("S_Playback_SpeechRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置播报速度百分比。.
        /// </summary>
        public static string S_Playback_SpeechRate_D {
            get {
                return ResourceManager.GetString("S_Playback_SpeechRate_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音音量.
        /// </summary>
        public static string S_Playback_Volume {
            get {
                return ResourceManager.GetString("S_Playback_Volume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置播报音量。.
        /// </summary>
        public static string S_Playback_Volume_D {
            get {
                return ResourceManager.GetString("S_Playback_Volume_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待播报完成.
        /// </summary>
        public static string S_Playback_WaitComplete {
            get {
                return ResourceManager.GetString("S_Playback_WaitComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待当前语音播报完成后再允许下一次抽取。.
        /// </summary>
        public static string S_Playback_WaitComplete_D {
            get {
                return ResourceManager.GetString("S_Playback_WaitComplete_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统音量.
        /// </summary>
        public static string S_SystemVolume {
            get {
                return ResourceManager.GetString("S_SystemVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用系统音量控制.
        /// </summary>
        public static string S_SystemVolume_Control {
            get {
                return ResourceManager.GetString("S_SystemVolume_Control", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 播报前自动调整系统音量。.
        /// </summary>
        public static string S_SystemVolume_Control_D {
            get {
                return ResourceManager.GetString("S_SystemVolume_Control_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统音量大小.
        /// </summary>
        public static string S_SystemVolume_Size {
            get {
                return ResourceManager.GetString("S_SystemVolume_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置语音播报时使用的系统音量。.
        /// </summary>
        public static string S_SystemVolume_Size_D {
            get {
                return ResourceManager.GetString("S_SystemVolume_Size_D", resourceCulture);
            }
        }

        public static string O_VoiceEngine_OmniTts {
            get {
                return ResourceManager.GetString("O_VoiceEngine_OmniTts", resourceCulture);
            }
        }

        public static string S_OmniTts {
            get {
                return ResourceManager.GetString("S_OmniTts", resourceCulture);
            }
        }

        public static string S_OmniTts_Provider {
            get {
                return ResourceManager.GetString("S_OmniTts_Provider", resourceCulture);
            }
        }

        public static string S_OmniTts_Provider_D {
            get {
                return ResourceManager.GetString("S_OmniTts_Provider_D", resourceCulture);
            }
        }

        public static string O_OmniTtsProvider_OpenAi {
            get {
                return ResourceManager.GetString("O_OmniTtsProvider_OpenAi", resourceCulture);
            }
        }

        public static string O_OmniTtsProvider_FishAudio {
            get {
                return ResourceManager.GetString("O_OmniTtsProvider_FishAudio", resourceCulture);
            }
        }

        public static string O_OmniTtsProvider_MiMo {
            get {
                return ResourceManager.GetString("O_OmniTtsProvider_MiMo", resourceCulture);
            }
        }

        public static string O_OmniTtsProvider_Custom {
            get {
                return ResourceManager.GetString("O_OmniTtsProvider_Custom", resourceCulture);
            }
        }

        public static string S_OmniTts_ApiBaseUrl {
            get {
                return ResourceManager.GetString("S_OmniTts_ApiBaseUrl", resourceCulture);
            }
        }

        public static string S_OmniTts_ApiBaseUrl_D {
            get {
                return ResourceManager.GetString("S_OmniTts_ApiBaseUrl_D", resourceCulture);
            }
        }

        public static string S_OmniTts_ApiKey {
            get {
                return ResourceManager.GetString("S_OmniTts_ApiKey", resourceCulture);
            }
        }

        public static string S_OmniTts_ApiKey_D {
            get {
                return ResourceManager.GetString("S_OmniTts_ApiKey_D", resourceCulture);
            }
        }

        public static string C_OmniTtsSaveKey {
            get {
                return ResourceManager.GetString("C_OmniTtsSaveKey", resourceCulture);
            }
        }

        public static string C_OmniTtsClearKey {
            get {
                return ResourceManager.GetString("C_OmniTtsClearKey", resourceCulture);
            }
        }

        public static string S_OmniTts_Model {
            get {
                return ResourceManager.GetString("S_OmniTts_Model", resourceCulture);
            }
        }

        public static string S_OmniTts_Model_D {
            get {
                return ResourceManager.GetString("S_OmniTts_Model_D", resourceCulture);
            }
        }

        public static string C_OmniTtsRefreshModels {
            get {
                return ResourceManager.GetString("C_OmniTtsRefreshModels", resourceCulture);
            }
        }

        public static string C_OmniTtsRefreshVoices {
            get {
                return ResourceManager.GetString("C_OmniTtsRefreshVoices", resourceCulture);
            }
        }

        public static string S_OmniTts_Voice {
            get {
                return ResourceManager.GetString("S_OmniTts_Voice", resourceCulture);
            }
        }

        public static string S_OmniTts_Voice_D {
            get {
                return ResourceManager.GetString("S_OmniTts_Voice_D", resourceCulture);
            }
        }

        public static string S_OmniTts_Instructions {
            get {
                return ResourceManager.GetString("S_OmniTts_Instructions", resourceCulture);
            }
        }

        public static string S_OmniTts_Instructions_D {
            get {
                return ResourceManager.GetString("S_OmniTts_Instructions_D", resourceCulture);
            }
        }

        public static string S_OmniTts_BatchGenerate {
            get {
                return ResourceManager.GetString("S_OmniTts_BatchGenerate", resourceCulture);
            }
        }

        public static string S_OmniTts_BatchGenerate_D {
            get {
                return ResourceManager.GetString("S_OmniTts_BatchGenerate_D", resourceCulture);
            }
        }

        public static string C_OmniTtsBatchTextHint {
            get {
                return ResourceManager.GetString("C_OmniTtsBatchTextHint", resourceCulture);
            }
        }

        public static string O_OmniTtsBatchSource_Text {
            get {
                return ResourceManager.GetString("O_OmniTtsBatchSource_Text", resourceCulture);
            }
        }

        public static string O_OmniTtsBatchSource_Students {
            get {
                return ResourceManager.GetString("O_OmniTtsBatchSource_Students", resourceCulture);
            }
        }

        public static string O_OmniTtsBatchSource_Prizes {
            get {
                return ResourceManager.GetString("O_OmniTtsBatchSource_Prizes", resourceCulture);
            }
        }

        public static string C_OmniTtsStartBatch {
            get {
                return ResourceManager.GetString("C_OmniTtsStartBatch", resourceCulture);
            }
        }

        public static string C_OmniTtsCancelBatch {
            get {
                return ResourceManager.GetString("C_OmniTtsCancelBatch", resourceCulture);
            }
        }

        public static string S_OmniTts_ClearCache {
            get {
                return ResourceManager.GetString("S_OmniTts_ClearCache", resourceCulture);
            }
        }

        public static string S_OmniTts_ClearCache_D {
            get {
                return ResourceManager.GetString("S_OmniTts_ClearCache_D", resourceCulture);
            }
        }

        public static string C_OmniTtsClearCache {
            get {
                return ResourceManager.GetString("C_OmniTtsClearCache", resourceCulture);
            }
        }

        public static string O_OmniTtsClearScope_All {
            get {
                return ResourceManager.GetString("O_OmniTtsClearScope_All", resourceCulture);
            }
        }

        public static string S_OmniTtsClearScope {
            get {
                return ResourceManager.GetString("S_OmniTtsClearScope", resourceCulture);
            }
        }

        public static string S_OmniTtsClearScope_D {
            get {
                return ResourceManager.GetString("S_OmniTtsClearScope_D", resourceCulture);
            }
        }

        public static string S_OmniTtsBatchScope {
            get {
                return ResourceManager.GetString("S_OmniTtsBatchScope", resourceCulture);
            }
        }

        public static string S_OmniTtsBatchScope_D {
            get {
                return ResourceManager.GetString("S_OmniTtsBatchScope_D", resourceCulture);
            }
        }

        public static string M_OmniTtsKeyConfigured {
            get {
                return ResourceManager.GetString("M_OmniTtsKeyConfigured", resourceCulture);
            }
        }

        public static string M_OmniTtsKeyNotConfigured {
            get {
                return ResourceManager.GetString("M_OmniTtsKeyNotConfigured", resourceCulture);
            }
        }

        public static string M_OmniTtsKeyEmpty {
            get {
                return ResourceManager.GetString("M_OmniTtsKeyEmpty", resourceCulture);
            }
        }

        public static string M_OmniTtsKeySaved {
            get {
                return ResourceManager.GetString("M_OmniTtsKeySaved", resourceCulture);
            }
        }

        public static string M_OmniTtsKeyCleared {
            get {
                return ResourceManager.GetString("M_OmniTtsKeyCleared", resourceCulture);
            }
        }

        public static string M_OmniTtsModelsRefreshed {
            get {
                return ResourceManager.GetString("M_OmniTtsModelsRefreshed", resourceCulture);
            }
        }

        public static string M_OmniTtsModelsEmpty {
            get {
                return ResourceManager.GetString("M_OmniTtsModelsEmpty", resourceCulture);
            }
        }

        public static string M_OmniTtsModelsRefreshFailed {
            get {
                return ResourceManager.GetString("M_OmniTtsModelsRefreshFailed", resourceCulture);
            }
        }

        public static string M_OmniTtsVoicesRefreshed {
            get {
                return ResourceManager.GetString("M_OmniTtsVoicesRefreshed", resourceCulture);
            }
        }

        public static string M_OmniTtsVoicesEmpty {
            get {
                return ResourceManager.GetString("M_OmniTtsVoicesEmpty", resourceCulture);
            }
        }

        public static string M_OmniTtsVoicesRefreshFailed {
            get {
                return ResourceManager.GetString("M_OmniTtsVoicesRefreshFailed", resourceCulture);
            }
        }

        public static string M_OmniTtsBatchStarted {
            get {
                return ResourceManager.GetString("M_OmniTtsBatchStarted", resourceCulture);
            }
        }

        public static string M_OmniTtsBatchProgress {
            get {
                return ResourceManager.GetString("M_OmniTtsBatchProgress", resourceCulture);
            }
        }

        public static string M_OmniTtsBatchCompleted {
            get {
                return ResourceManager.GetString("M_OmniTtsBatchCompleted", resourceCulture);
            }
        }

        public static string M_OmniTtsBatchCompletedToast {
            get {
                return ResourceManager.GetString("M_OmniTtsBatchCompletedToast", resourceCulture);
            }
        }

        public static string M_OmniTtsBatchCancelled {
            get {
                return ResourceManager.GetString("M_OmniTtsBatchCancelled", resourceCulture);
            }
        }

        public static string M_OmniTtsBatchFailed {
            get {
                return ResourceManager.GetString("M_OmniTtsBatchFailed", resourceCulture);
            }
        }

        public static string M_OmniTtsCacheCleared {
            get {
                return ResourceManager.GetString("M_OmniTtsCacheCleared", resourceCulture);
            }
        }

        public static string M_OmniTtsCacheEmpty {
            get {
                return ResourceManager.GetString("M_OmniTtsCacheEmpty", resourceCulture);
            }
        }
    }
}
