//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Voice {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Voice.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edge TTS.
        /// </summary>
        public static string O_VoiceEngine_EdgeTts {
            get {
                return ResourceManager.GetString("O_VoiceEngine_EdgeTts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统语音.
        /// </summary>
        public static string O_VoiceEngine_System {
            get {
                return ResourceManager.GetString("O_VoiceEngine_System", resourceCulture);
            }
        }

        public static string C_RefreshVoices {
            get {
                return ResourceManager.GetString("C_RefreshVoices", resourceCulture);
            }
        }

        public static string C_TestVoice {
            get {
                return ResourceManager.GetString("C_TestVoice", resourceCulture);
            }
        }

        public static string C_TestVoiceText {
            get {
                return ResourceManager.GetString("C_TestVoiceText", resourceCulture);
            }
        }

        public static string M_TestVoiceCompleted {
            get {
                return ResourceManager.GetString("M_TestVoiceCompleted", resourceCulture);
            }
        }

        public static string M_TestVoiceFailed {
            get {
                return ResourceManager.GetString("M_TestVoiceFailed", resourceCulture);
            }
        }

        public static string M_VoicesRefreshed {
            get {
                return ResourceManager.GetString("M_VoicesRefreshed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音设置.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 播报内容.
        /// </summary>
        public static string S_Content {
            get {
                return ResourceManager.GetString("S_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 播报编号.
        /// </summary>
        public static string S_Content_AnnounceId {
            get {
                return ResourceManager.GetString("S_Content_AnnounceId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 结果中包含编号。.
        /// </summary>
        public static string S_Content_AnnounceId_D {
            get {
                return ResourceManager.GetString("S_Content_AnnounceId_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 播报姓名.
        /// </summary>
        public static string S_Content_AnnounceName {
            get {
                return ResourceManager.GetString("S_Content_AnnounceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 结果中包含姓名。.
        /// </summary>
        public static string S_Content_AnnounceName_D {
            get {
                return ResourceManager.GetString("S_Content_AnnounceName_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音播报.
        /// </summary>
        public static string S_Playback {
            get {
                return ResourceManager.GetString("S_Playback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edge TTS 音色.
        /// </summary>
        public static string S_Playback_EdgeTtsVoice {
            get {
                return ResourceManager.GetString("S_Playback_EdgeTtsVoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edge TTS 使用的 voice 名称。.
        /// </summary>
        public static string S_Playback_EdgeTtsVoice_D {
            get {
                return ResourceManager.GetString("S_Playback_EdgeTtsVoice_D", resourceCulture);
            }
        }

        public static string S_Playback_Actions {
            get {
                return ResourceManager.GetString("S_Playback_Actions", resourceCulture);
            }
        }

        public static string S_Playback_Actions_D {
            get {
                return ResourceManager.GetString("S_Playback_Actions_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用语音播报.
        /// </summary>
        public static string S_Playback_Enable {
            get {
                return ResourceManager.GetString("S_Playback_Enable", resourceCulture);
            }
        }

        public static string S_Playback_Voice {
            get {
                return ResourceManager.GetString("S_Playback_Voice", resourceCulture);
            }
        }

        public static string S_Playback_Voice_D {
            get {
                return ResourceManager.GetString("S_Playback_Voice_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 作为所有抽取语音播报的总开关；各抽取设置可单独控制是否播报。.
        /// </summary>
        public static string S_Playback_Enable_D {
            get {
                return ResourceManager.GetString("S_Playback_Enable_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音引擎.
        /// </summary>
        public static string S_Playback_Engine {
            get {
                return ResourceManager.GetString("S_Playback_Engine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择用于播报的语音引擎。.
        /// </summary>
        public static string S_Playback_Engine_D {
            get {
                return ResourceManager.GetString("S_Playback_Engine_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语速.
        /// </summary>
        public static string S_Playback_SpeechRate {
            get {
                return ResourceManager.GetString("S_Playback_SpeechRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置播报速度百分比。.
        /// </summary>
        public static string S_Playback_SpeechRate_D {
            get {
                return ResourceManager.GetString("S_Playback_SpeechRate_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音音量.
        /// </summary>
        public static string S_Playback_Volume {
            get {
                return ResourceManager.GetString("S_Playback_Volume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置播报音量。.
        /// </summary>
        public static string S_Playback_Volume_D {
            get {
                return ResourceManager.GetString("S_Playback_Volume_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待播报完成.
        /// </summary>
        public static string S_Playback_WaitComplete {
            get {
                return ResourceManager.GetString("S_Playback_WaitComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待当前语音播报完成后再允许下一次抽取。.
        /// </summary>
        public static string S_Playback_WaitComplete_D {
            get {
                return ResourceManager.GetString("S_Playback_WaitComplete_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统音量.
        /// </summary>
        public static string S_SystemVolume {
            get {
                return ResourceManager.GetString("S_SystemVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用系统音量控制.
        /// </summary>
        public static string S_SystemVolume_Control {
            get {
                return ResourceManager.GetString("S_SystemVolume_Control", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 播报前自动调整系统音量。.
        /// </summary>
        public static string S_SystemVolume_Control_D {
            get {
                return ResourceManager.GetString("S_SystemVolume_Control_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统音量大小.
        /// </summary>
        public static string S_SystemVolume_Size {
            get {
                return ResourceManager.GetString("S_SystemVolume_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置语音播报时使用的系统音量。.
        /// </summary>
        public static string S_SystemVolume_Size_D {
            get {
                return ResourceManager.GetString("S_SystemVolume_Size_D", resourceCulture);
            }
        }
    }
}
