//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Plugins.Overview
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources()
        {
        }

        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Plugins.Overview.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        public static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Page_Title => ResourceManager.GetString("Page_Title", resourceCulture);
        public static string C_ImportPlugin => ResourceManager.GetString("C_ImportPlugin", resourceCulture);
        public static string C_Refresh => ResourceManager.GetString("C_Refresh", resourceCulture);
        public static string C_OpenPluginsFolder => ResourceManager.GetString("C_OpenPluginsFolder", resourceCulture);
        public static string C_MoreOptions => ResourceManager.GetString("C_MoreOptions", resourceCulture);
        public static string C_SearchPlugin => ResourceManager.GetString("C_SearchPlugin", resourceCulture);
        public static string C_NoPluginSelected => ResourceManager.GetString("C_NoPluginSelected", resourceCulture);
        public static string C_OverviewEmptyTitle => ResourceManager.GetString("C_OverviewEmptyTitle", resourceCulture);
        public static string C_OverviewEmptyHint => ResourceManager.GetString("C_OverviewEmptyHint", resourceCulture);
        public static string C_ImportHint => ResourceManager.GetString("C_ImportHint", resourceCulture);
        public static string C_Importing => ResourceManager.GetString("C_Importing", resourceCulture);
        public static string C_FilterAll => ResourceManager.GetString("C_FilterAll", resourceCulture);
        public static string C_FilterMarket => ResourceManager.GetString("C_FilterMarket", resourceCulture);
        public static string C_FilterInstalled => ResourceManager.GetString("C_FilterInstalled", resourceCulture);
        public static string C_FilterNotInstalled => ResourceManager.GetString("C_FilterNotInstalled", resourceCulture);
        public static string C_FilterEnabled => ResourceManager.GetString("C_FilterEnabled", resourceCulture);
        public static string C_FilterDisabled => ResourceManager.GetString("C_FilterDisabled", resourceCulture);
        public static string C_FilterPending => ResourceManager.GetString("C_FilterPending", resourceCulture);
        public static string C_FilterError => ResourceManager.GetString("C_FilterError", resourceCulture);
        public static string C_LocalImport => ResourceManager.GetString("C_LocalImport", resourceCulture);
        public static string C_OpenSelectedFolder => ResourceManager.GetString("C_OpenSelectedFolder", resourceCulture);
        public static string C_SourceUrl => ResourceManager.GetString("C_SourceUrl", resourceCulture);
        public static string C_SourceMirrorUrl => ResourceManager.GetString("C_SourceMirrorUrl", resourceCulture);
        public static string C_AddSource => ResourceManager.GetString("C_AddSource", resourceCulture);
        public static string C_RefreshCatalog => ResourceManager.GetString("C_RefreshCatalog", resourceCulture);
        public static string C_CatalogSources => ResourceManager.GetString("C_CatalogSources", resourceCulture);
        public static string C_ManagePluginSources => ResourceManager.GetString("C_ManagePluginSources", resourceCulture);
        public static string C_BuiltInPluginSource => ResourceManager.GetString("C_BuiltInPluginSource", resourceCulture);
        public static string C_BuiltInPluginSourceMirror => ResourceManager.GetString("C_BuiltInPluginSourceMirror", resourceCulture);
        public static string C_IgnoreTlsCertificateErrors => ResourceManager.GetString("C_IgnoreTlsCertificateErrors", resourceCulture);
        public static string C_CustomPluginSource => ResourceManager.GetString("C_CustomPluginSource", resourceCulture);
        public static string C_Add => ResourceManager.GetString("C_Add", resourceCulture);
        public static string C_Delete => ResourceManager.GetString("C_Delete", resourceCulture);
        public static string C_SourceUrlColumn => ResourceManager.GetString("C_SourceUrlColumn", resourceCulture);
        public static string C_SourceMirrorColumn => ResourceManager.GetString("C_SourceMirrorColumn", resourceCulture);
        public static string C_UpdateSource => ResourceManager.GetString("C_UpdateSource", resourceCulture);
        public static string C_Catalog => ResourceManager.GetString("C_Catalog", resourceCulture);
        public static string C_CatalogEmpty => ResourceManager.GetString("C_CatalogEmpty", resourceCulture);
        public static string C_Install => ResourceManager.GetString("C_Install", resourceCulture);
        public static string C_Enable => ResourceManager.GetString("C_Enable", resourceCulture);
        public static string C_Disable => ResourceManager.GetString("C_Disable", resourceCulture);
        public static string C_NoPluginSelectedHint => ResourceManager.GetString("C_NoPluginSelectedHint", resourceCulture);
        public static string C_InstalledPluginCount => ResourceManager.GetString("C_InstalledPluginCount", resourceCulture);
        public static string C_VisiblePluginCount => ResourceManager.GetString("C_VisiblePluginCount", resourceCulture);
        public static string C_PluginCount => ResourceManager.GetString("C_PluginCount", resourceCulture);
        public static string C_NoDescription => ResourceManager.GetString("C_NoDescription", resourceCulture);
        public static string C_Unknown => ResourceManager.GetString("C_Unknown", resourceCulture);
        public static string C_Readme => ResourceManager.GetString("C_Readme", resourceCulture);
        public static string C_None => ResourceManager.GetString("C_None", resourceCulture);
        public static string S_Status => ResourceManager.GetString("S_Status", resourceCulture);
        public static string S_Directory => ResourceManager.GetString("S_Directory", resourceCulture);
        public static string S_Error => ResourceManager.GetString("S_Error", resourceCulture);
        public static string S_Author => ResourceManager.GetString("S_Author", resourceCulture);
        public static string S_ApiVersion => ResourceManager.GetString("S_ApiVersion", resourceCulture);
        public static string S_MinimumHostVersion => ResourceManager.GetString("S_MinimumHostVersion", resourceCulture);
        public static string S_Description => ResourceManager.GetString("S_Description", resourceCulture);
        public static string S_StatusDiscovered => ResourceManager.GetString("S_StatusDiscovered", resourceCulture);
        public static string S_StatusNotEnabled => ResourceManager.GetString("S_StatusNotEnabled", resourceCulture);
        public static string S_StatusDisabled => ResourceManager.GetString("S_StatusDisabled", resourceCulture);
        public static string S_StatusLoaded => ResourceManager.GetString("S_StatusLoaded", resourceCulture);
        public static string S_StatusLoadFailed => ResourceManager.GetString("S_StatusLoadFailed", resourceCulture);
        public static string S_StatusIncompatible => ResourceManager.GetString("S_StatusIncompatible", resourceCulture);
        public static string S_StatusPendingRestart => ResourceManager.GetString("S_StatusPendingRestart", resourceCulture);
        public static string S_StatusAvailable => ResourceManager.GetString("S_StatusAvailable", resourceCulture);
        public static string M_SelectPluginFolderTitle => ResourceManager.GetString("M_SelectPluginFolderTitle", resourceCulture);
        public static string M_SelectPluginPackageTitle => ResourceManager.GetString("M_SelectPluginPackageTitle", resourceCulture);
        public static string M_SecRandomPluginPackageFileType => ResourceManager.GetString("M_SecRandomPluginPackageFileType", resourceCulture);
        public static string M_InvalidPluginFolder => ResourceManager.GetString("M_InvalidPluginFolder", resourceCulture);
        public static string M_InvalidPluginPackage => ResourceManager.GetString("M_InvalidPluginPackage", resourceCulture);
        public static string M_PluginImported => ResourceManager.GetString("M_PluginImported", resourceCulture);
        public static string M_PluginImportExists => ResourceManager.GetString("M_PluginImportExists", resourceCulture);
        public static string M_PluginImportFailed => ResourceManager.GetString("M_PluginImportFailed", resourceCulture);
        public static string M_PluginImportNeedsRestart => ResourceManager.GetString("M_PluginImportNeedsRestart", resourceCulture);
        public static string M_CatalogRefreshFailed => ResourceManager.GetString("M_CatalogRefreshFailed", resourceCulture);
        public static string M_SourceAddFailed => ResourceManager.GetString("M_SourceAddFailed", resourceCulture);
        public static string C_Uninstall => ResourceManager.GetString("C_Uninstall", resourceCulture);
        public static string M_UninstallConfirmTitle => ResourceManager.GetString("M_UninstallConfirmTitle", resourceCulture);
        public static string M_UninstallConfirm => ResourceManager.GetString("M_UninstallConfirm", resourceCulture);
        public static string M_UninstallFailed => ResourceManager.GetString("M_UninstallFailed", resourceCulture);
        public static string M_IndexInvalid => ResourceManager.GetString("M_IndexInvalid", resourceCulture);
        public static string M_IndexSignatureInvalid => ResourceManager.GetString("M_IndexSignatureInvalid", resourceCulture);
        public static string M_PublicKeyInvalid => ResourceManager.GetString("M_PublicKeyInvalid", resourceCulture);
        public static string M_DownloadUrlMissing => ResourceManager.GetString("M_DownloadUrlMissing", resourceCulture);
        public static string M_PackageHashMismatch => ResourceManager.GetString("M_PackageHashMismatch", resourceCulture);
        public static string M_DependencyMissing => ResourceManager.GetString("M_DependencyMissing", resourceCulture);
        public static string M_DependencyCycle => ResourceManager.GetString("M_DependencyCycle", resourceCulture);
        public static string M_InstallConfirm => ResourceManager.GetString("M_InstallConfirm", resourceCulture);
        public static string M_InstallDependencies => ResourceManager.GetString("M_InstallDependencies", resourceCulture);
        public static string C_Update => ResourceManager.GetString("C_Update", resourceCulture);
        public static string C_Installed => ResourceManager.GetString("C_Installed", resourceCulture);
        public static string C_Incompatible => ResourceManager.GetString("C_Incompatible", resourceCulture);
        public static string C_Refreshing => ResourceManager.GetString("C_Refreshing", resourceCulture);
        public static string C_CatalogRefreshHint => ResourceManager.GetString("C_CatalogRefreshHint", resourceCulture);
        public static string C_Dependencies => ResourceManager.GetString("C_Dependencies", resourceCulture);
        public static string C_ProjectUrl => ResourceManager.GetString("C_ProjectUrl", resourceCulture);
        public static string M_InstallConfirmTitle => ResourceManager.GetString("M_InstallConfirmTitle", resourceCulture);
    }
}
