//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SecRandom.Langs.MainPages.QuickDraw;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal Resources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager => resourceMan ??=
        new global::System.Resources.ResourceManager("SecRandom.Langs.MainPages.QuickDraw.Resources", typeof(Resources).Assembly);

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string C_Start => ResourceManager.GetString(nameof(C_Start), resourceCulture)!;
    public static string C_Stop => ResourceManager.GetString(nameof(C_Stop), resourceCulture)!;
    public static string M_DefaultListMissing => ResourceManager.GetString(nameof(M_DefaultListMissing), resourceCulture)!;
    public static string M_DefaultListRequired => ResourceManager.GetString(nameof(M_DefaultListRequired), resourceCulture)!;
    public static string M_DrawFailed => ResourceManager.GetString(nameof(M_DrawFailed), resourceCulture)!;
    public static string M_Drawing => ResourceManager.GetString(nameof(M_Drawing), resourceCulture)!;
    public static string M_DrawnCountFormat => ResourceManager.GetString(nameof(M_DrawnCountFormat), resourceCulture)!;
    public static string M_NoMembers => ResourceManager.GetString(nameof(M_NoMembers), resourceCulture)!;
    public static string M_Ready => ResourceManager.GetString(nameof(M_Ready), resourceCulture)!;
    public static string M_ResetDone => ResourceManager.GetString(nameof(M_ResetDone), resourceCulture)!;
}
