//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.General.Backup {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.General.Backup.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string C_Backups_DateTime {
            get {
                return ResourceManager.GetString("C_Backups_DateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 文件名.
        /// </summary>
        public static string C_Backups_FileName {
            get {
                return ResourceManager.GetString("C_Backups_FileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string C_Backups_Operations {
            get {
                return ResourceManager.GetString("C_Backups_Operations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string C_Backups_Operations_Delete {
            get {
                return ResourceManager.GetString("C_Backups_Operations_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复.
        /// </summary>
        public static string C_Backups_Operations_Restore {
            get {
                return ResourceManager.GetString("C_Backups_Operations_Restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 大小.
        /// </summary>
        public static string C_Backups_Size {
            get {
                return ResourceManager.GetString("C_Backups_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 刷新备份.
        /// </summary>
        public static string C_RefreshBackups {
            get {
                return ResourceManager.GetString("C_RefreshBackups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已创建备份：{0}.
        /// </summary>
        public static string M_BackupCreated {
            get {
                return ResourceManager.GetString("M_BackupCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份失败.
        /// </summary>
        public static string M_BackupFailed {
            get {
                return ResourceManager.GetString("M_BackupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份文件不存在，请刷新后重试.
        /// </summary>
        public static string M_BackupFileMissing {
            get {
                return ResourceManager.GetString("M_BackupFileMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 确定要删除备份“{0}”吗？此操作无法撤销。.
        /// </summary>
        public static string M_DeleteContent {
            get {
                return ResourceManager.GetString("M_DeleteContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除备份失败.
        /// </summary>
        public static string M_DeleteFailed {
            get {
                return ResourceManager.GetString("M_DeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string M_DeletePrimary {
            get {
                return ResourceManager.GetString("M_DeletePrimary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已删除备份.
        /// </summary>
        public static string M_DeleteSuccess {
            get {
                return ResourceManager.GetString("M_DeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除备份.
        /// </summary>
        public static string M_DeleteTitle {
            get {
                return ResourceManager.GetString("M_DeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份文件包含非法路径，已取消恢复.
        /// </summary>
        public static string M_InvalidBackupFile {
            get {
                return ResourceManager.GetString("M_InvalidBackupFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请至少选择一项备份内容.
        /// </summary>
        public static string M_NoBackupContentSelected {
            get {
                return ResourceManager.GetString("M_NoBackupContentSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复“{0}”会覆盖当前对应数据。恢复前会自动创建一份当前数据快照，恢复完成后需要重启应用。.
        /// </summary>
        public static string M_RestoreContent {
            get {
                return ResourceManager.GetString("M_RestoreContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复备份失败.
        /// </summary>
        public static string M_RestoreFailed {
            get {
                return ResourceManager.GetString("M_RestoreFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复.
        /// </summary>
        public static string M_RestorePrimary {
            get {
                return ResourceManager.GetString("M_RestorePrimary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份已恢复，请重启应用后生效.
        /// </summary>
        public static string M_RestoreSuccess {
            get {
                return ResourceManager.GetString("M_RestoreSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复备份.
        /// </summary>
        public static string M_RestoreTitle {
            get {
                return ResourceManager.GetString("M_RestoreTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动备份.
        /// </summary>
        public static string S_AutoBackup {
            get {
                return ResourceManager.GetString("S_AutoBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 是否启用自动备份.
        /// </summary>
        public static string S_AutoBackup_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动备份间隔.
        /// </summary>
        public static string S_AutoBackup_IntervalDays {
            get {
                return ResourceManager.GetString("S_AutoBackup_IntervalDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置自动备份间隔（天）.
        /// </summary>
        public static string S_AutoBackup_IntervalDays_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_IntervalDays_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即备份.
        /// </summary>
        public static string S_AutoBackup_ManualBackup {
            get {
                return ResourceManager.GetString("S_AutoBackup_ManualBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即创建一份全量备份.
        /// </summary>
        public static string S_AutoBackup_ManualBackup_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_ManualBackup_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动备份上限.
        /// </summary>
        public static string S_AutoBackup_MaxCount {
            get {
                return ResourceManager.GetString("S_AutoBackup_MaxCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置自动备份最多保留数量（个），0为不限制.
        /// </summary>
        public static string S_AutoBackup_MaxCount_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_MaxCount_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份占用大小.
        /// </summary>
        public static string S_AutoBackup_Usage {
            get {
                return ResourceManager.GetString("S_AutoBackup_Usage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份文件夹占用大小.
        /// </summary>
        public static string S_AutoBackup_Usage_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_Usage_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 占用大小.
        /// </summary>
        public static string S_AutoBackup_Usage_R {
            get {
                return ResourceManager.GetString("S_AutoBackup_Usage_R", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 查看备份文件.
        /// </summary>
        public static string S_AutoBackup_ViewFolder {
            get {
                return ResourceManager.GetString("S_AutoBackup_ViewFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开备份文件夹.
        /// </summary>
        public static string S_AutoBackup_ViewFolder_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_ViewFolder_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份内容.
        /// </summary>
        public static string S_Includes {
            get {
                return ResourceManager.GetString("S_Includes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 音频资源.
        /// </summary>
        public static string S_Includes_Audio {
            get {
                return ResourceManager.GetString("S_Includes_Audio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 音频资源文件（audio）.
        /// </summary>
        public static string S_Includes_Audio_D {
            get {
                return ResourceManager.GetString("S_Includes_Audio_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 配置文件.
        /// </summary>
        public static string S_Includes_Config {
            get {
                return ResourceManager.GetString("S_Includes_Config", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 软件设置与配置文件（config）.
        /// </summary>
        public static string S_Includes_Config_D {
            get {
                return ResourceManager.GetString("S_Includes_Config_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CSES 联动.
        /// </summary>
        public static string S_Includes_Cses {
            get {
                return ResourceManager.GetString("S_Includes_Cses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CSES 相关联动数据（CSES）.
        /// </summary>
        public static string S_Includes_Cses_D {
            get {
                return ResourceManager.GetString("S_Includes_Cses_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择需要包含在备份文件中的数据.
        /// </summary>
        public static string S_Includes_D {
            get {
                return ResourceManager.GetString("S_Includes_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string S_Includes_History {
            get {
                return ResourceManager.GetString("S_Includes_History", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取历史记录数据（history）.
        /// </summary>
        public static string S_Includes_History_D {
            get {
                return ResourceManager.GetString("S_Includes_History_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取证明文件.
        /// </summary>
        public static string S_Includes_Proofs {
            get {
                return ResourceManager.GetString("S_Includes_Proofs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 可复现和核验抽取结果的证明文件（proofs）.
        /// </summary>
        public static string S_Includes_Proofs_D {
            get {
                return ResourceManager.GetString("S_Includes_Proofs_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 图片资源.
        /// </summary>
        public static string S_Includes_Images {
            get {
                return ResourceManager.GetString("S_Includes_Images", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 学生/奖品图片资源（images）.
        /// </summary>
        public static string S_Includes_Images_D {
            get {
                return ResourceManager.GetString("S_Includes_Images_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 名单数据.
        /// </summary>
        public static string S_Includes_List {
            get {
                return ResourceManager.GetString("S_Includes_List", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点名/抽奖名单等数据（list）.
        /// </summary>
        public static string S_Includes_List_D {
            get {
                return ResourceManager.GetString("S_Includes_List_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 运行日志.
        /// </summary>
        public static string S_Includes_Logs {
            get {
                return ResourceManager.GetString("S_Includes_Logs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 程序运行日志，可能包含敏感信息（logs）.
        /// </summary>
        public static string S_Includes_Logs_D {
            get {
                return ResourceManager.GetString("S_Includes_Logs_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 主题资源.
        /// </summary>
        public static string S_Includes_Themes {
            get {
                return ResourceManager.GetString("S_Includes_Themes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已安装的主题资源（theme）.
        /// </summary>
        public static string S_Includes_Themes_D {
            get {
                return ResourceManager.GetString("S_Includes_Themes_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复备份.
        /// </summary>
        public static string S_RestoreBackup {
            get {
                return ResourceManager.GetString("S_RestoreBackup", resourceCulture);
            }
        }
    }
}
