// <auto-generated />
#nullable enable
namespace SecRandom.Langs.SettingsPages.Debug;

using System.Globalization;
using System.Resources;

public class DebugStrings
{
    private static readonly ResourceManager ResourceManagerInstance = new(
        "SecRandom.Langs.SettingsPages.Debug.Resources", typeof(DebugStrings).Assembly);

    public static CultureInfo? Culture { get; set; }
    public static string Get(string key) => ResourceManagerInstance.GetString(key, Culture) ?? key;
    public static string Page_Title => Get(nameof(Page_Title));
    public string C_DrawerTest => Get(nameof(C_DrawerTest));
    public string C_HideDebugEntry => Get(nameof(C_HideDebugEntry));
    public string C_HideDebugEntry_D => Get(nameof(C_HideDebugEntry_D));
    public string C_Hide => Get(nameof(C_Hide));
    public string S_UiTests => Get(nameof(S_UiTests));
    public string C_SendToast => Get(nameof(C_SendToast));
    public string C_OpenDrawer => Get(nameof(C_OpenDrawer));
    public string S_CrashRecovery => Get(nameof(S_CrashRecovery));
    public string C_ShowCrashRecovery => Get(nameof(C_ShowCrashRecovery));
    public string C_ThrowDispatcherException => Get(nameof(C_ThrowDispatcherException));
    public string C_RestartProgram => Get(nameof(C_RestartProgram));
    public string S_Plugins => Get(nameof(S_Plugins));
    public string C_ShowPluginSettings => Get(nameof(C_ShowPluginSettings));
    public string C_ShowPluginSettings_D => Get(nameof(C_ShowPluginSettings_D));
    public string S_InternalSettings => Get(nameof(S_InternalSettings));
    public string C_EnableInternalSettings => Get(nameof(C_EnableInternalSettings));
    public string C_EnableInternalSettings_D => Get(nameof(C_EnableInternalSettings_D));
    public string S_UpdateDiagnostics => Get(nameof(S_UpdateDiagnostics));
    public string C_RefreshUpdate => Get(nameof(C_RefreshUpdate));
    public string C_RefreshUpdate_D => Get(nameof(C_RefreshUpdate_D));
    public string S_LinkageNotificationDiagnostics => Get(nameof(S_LinkageNotificationDiagnostics));
    public string C_RefreshLinkage => Get(nameof(C_RefreshLinkage));
    public string C_RefreshLinkage_D => Get(nameof(C_RefreshLinkage_D));
    public string S_PlatformDiagnostics => Get(nameof(S_PlatformDiagnostics));
    public string C_RefreshPlatform => Get(nameof(C_RefreshPlatform));
    public string C_RefreshPlatform_D => Get(nameof(C_RefreshPlatform_D));
    public string S_DataPathDiagnostics => Get(nameof(S_DataPathDiagnostics));
    public string C_RefreshPaths => Get(nameof(C_RefreshPaths));
    public string C_RefreshPaths_D => Get(nameof(C_RefreshPaths_D));
}
