//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.General.Privacy {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.General.Privacy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 匿名上报.
        /// </summary>
        public static string O_OnlineStatusMode_Anonymous {
            get {
                return ResourceManager.GetString("O_OnlineStatusMode_Anonymous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 完整上报.
        /// </summary>
        public static string O_OnlineStatusMode_Full {
            get {
                return ResourceManager.GetString("O_OnlineStatusMode_Full", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 停止上报.
        /// </summary>
        public static string O_OnlineStatusMode_Off {
            get {
                return ResourceManager.GetString("O_OnlineStatusMode_Off", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 隐私.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在线状态统计.
        /// </summary>
        public static string S_OnlineStatus {
            get {
                return ResourceManager.GetString("S_OnlineStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在线状态.
        /// </summary>
        public static string S_OnlineStatus_Mode {
            get {
                return ResourceManager.GetString("S_OnlineStatus_Mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 完整上报包含粗略位置信息，匿名上报仅计入在线人数不报位置，停止则不上报在线状态。.
        /// </summary>
        public static string S_OnlineStatus_Mode_D {
            get {
                return ResourceManager.GetString("S_OnlineStatus_Mode_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sentry 遥测.
        /// </summary>
        public static string S_SentryTelemetry {
            get {
                return ResourceManager.GetString("S_SentryTelemetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用 Sentry 遥测.
        /// </summary>
        public static string S_SentryTelemetry_Enabled {
            get {
                return ResourceManager.GetString("S_SentryTelemetry_Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开启后上传崩溃、日志、追踪和性能分析数据；不会控制在线状态统计。.
        /// </summary>
        public static string S_SentryTelemetry_Enabled_D {
            get {
                return ResourceManager.GetString("S_SentryTelemetry_Enabled_D", resourceCulture);
            }
        }
    }
}
