//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.LogViewer {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.LogViewer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string C_Cancel => ResourceManager.GetString("C_Cancel", resourceCulture);
        public static string C_ColumnCategory => ResourceManager.GetString("C_ColumnCategory", resourceCulture);
        public static string C_ColumnLevel => ResourceManager.GetString("C_ColumnLevel", resourceCulture);
        public static string C_ColumnMessage => ResourceManager.GetString("C_ColumnMessage", resourceCulture);
        public static string C_ColumnTime => ResourceManager.GetString("C_ColumnTime", resourceCulture);
        public static string C_CopySelected => ResourceManager.GetString("C_CopySelected", resourceCulture);
        public static string C_CurrentFileName => ResourceManager.GetString("C_CurrentFileName", resourceCulture);
        public static string C_DeleteSelected => ResourceManager.GetString("C_DeleteSelected", resourceCulture);
        public static string C_EntryCount => ResourceManager.GetString("C_EntryCount", resourceCulture);
        public static string C_FileInfo => ResourceManager.GetString("C_FileInfo", resourceCulture);
        public static string C_OpenFolder => ResourceManager.GetString("C_OpenFolder", resourceCulture);
        public static string C_Refresh => ResourceManager.GetString("C_Refresh", resourceCulture);
        public static string C_SearchWatermark => ResourceManager.GetString("C_SearchWatermark", resourceCulture);
        public static string M_Copied => ResourceManager.GetString("M_Copied", resourceCulture);
        public static string M_DeleteContent => ResourceManager.GetString("M_DeleteContent", resourceCulture);
        public static string M_DeleteFailed => ResourceManager.GetString("M_DeleteFailed", resourceCulture);
        public static string M_DeletePrimary => ResourceManager.GetString("M_DeletePrimary", resourceCulture);
        public static string M_DeleteSuccess => ResourceManager.GetString("M_DeleteSuccess", resourceCulture);
        public static string M_DeleteTitle => ResourceManager.GetString("M_DeleteTitle", resourceCulture);
        public static string M_LoadFailed => ResourceManager.GetString("M_LoadFailed", resourceCulture);
        public static string M_SelectEntry => ResourceManager.GetString("M_SelectEntry", resourceCulture);
        public static string O_Level_All => ResourceManager.GetString("O_Level_All", resourceCulture);
        public static string O_Level_Critical => ResourceManager.GetString("O_Level_Critical", resourceCulture);
        public static string O_Level_Debug => ResourceManager.GetString("O_Level_Debug", resourceCulture);
        public static string O_Level_Error => ResourceManager.GetString("O_Level_Error", resourceCulture);
        public static string O_Level_Information => ResourceManager.GetString("O_Level_Information", resourceCulture);
        public static string O_Level_Trace => ResourceManager.GetString("O_Level_Trace", resourceCulture);
        public static string O_Level_Warning => ResourceManager.GetString("O_Level_Warning", resourceCulture);
        public static string Page_Title => ResourceManager.GetString("Page_Title", resourceCulture);
    }
}
