//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.HistoryManagement {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.HistoryManagement.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 历史记录管理.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 筛选.
        /// </summary>
        public static string S_Filter {
            get {
                return ResourceManager.GetString("S_Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 默认班级筛选.
        /// </summary>
        public static string S_Filter_SelectedClassName {
            get {
                return ResourceManager.GetString("S_Filter_SelectedClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 进入历史页时默认选择的班级。.
        /// </summary>
        public static string S_Filter_SelectedClassName_D {
            get {
                return ResourceManager.GetString("S_Filter_SelectedClassName_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 默认奖池筛选.
        /// </summary>
        public static string S_Filter_SelectedPoolName {
            get {
                return ResourceManager.GetString("S_Filter_SelectedPoolName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 进入历史页时默认选择的奖池。.
        /// </summary>
        public static string S_Filter_SelectedPoolName_D {
            get {
                return ResourceManager.GetString("S_Filter_SelectedPoolName_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string S_History {
            get {
                return ResourceManager.GetString("S_History", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示权重信息.
        /// </summary>
        public static string S_History_SelectWeight {
            get {
                return ResourceManager.GetString("S_History_SelectWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 查看历史记录时显示参与抽取的权重信息。.
        /// </summary>
        public static string S_History_SelectWeight_D {
            get {
                return ResourceManager.GetString("S_History_SelectWeight_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示抽奖历史.
        /// </summary>
        public static string S_History_ShowLottery {
            get {
                return ResourceManager.GetString("S_History_ShowLottery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在历史页中显示抽奖记录。.
        /// </summary>
        public static string S_History_ShowLottery_D {
            get {
                return ResourceManager.GetString("S_History_ShowLottery_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示点名历史.
        /// </summary>
        public static string S_History_ShowRollCall {
            get {
                return ResourceManager.GetString("S_History_ShowRollCall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在历史页中显示点名记录。.
        /// </summary>
        public static string S_History_ShowRollCall_D {
            get {
                return ResourceManager.GetString("S_History_ShowRollCall_D", resourceCulture);
            }
        }

        public static string S_ClearHistory {
            get {
                return ResourceManager.GetString("S_ClearHistory", resourceCulture);
            }
        }

        public static string S_ClearHistory_RollCall {
            get {
                return ResourceManager.GetString("S_ClearHistory_RollCall", resourceCulture);
            }
        }

        public static string S_ClearHistory_RollCall_D {
            get {
                return ResourceManager.GetString("S_ClearHistory_RollCall_D", resourceCulture);
            }
        }

        public static string S_ClearHistory_Lottery {
            get {
                return ResourceManager.GetString("S_ClearHistory_Lottery", resourceCulture);
            }
        }

        public static string S_ClearHistory_Lottery_D {
            get {
                return ResourceManager.GetString("S_ClearHistory_Lottery_D", resourceCulture);
            }
        }

        public static string C_Clear {
            get {
                return ResourceManager.GetString("C_Clear", resourceCulture);
            }
        }

        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }

        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }

        public static string M_ClearConfirm_Title {
            get {
                return ResourceManager.GetString("M_ClearConfirm_Title", resourceCulture);
            }
        }

        public static string M_ClearConfirm_Content {
            get {
                return ResourceManager.GetString("M_ClearConfirm_Content", resourceCulture);
            }
        }

        public static string M_ClearSuccess {
            get {
                return ResourceManager.GetString("M_ClearSuccess", resourceCulture);
            }
        }

        public static string M_ClearFailed {
            get {
                return ResourceManager.GetString("M_ClearFailed", resourceCulture);
            }
        }

        public static string M_SelectFirst {
            get {
                return ResourceManager.GetString("M_SelectFirst", resourceCulture);
            }
        }
    }
}
