//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.MainPages.History {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.MainPages.History.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课间.
        /// </summary>
        public static string C_Break {
            get {
                return ResourceManager.GetString("C_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机抽取.
        /// </summary>
        public static string C_MethodRandom {
            get {
                return ResourceManager.GetString("C_MethodRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公平抽取.
        /// </summary>
        public static string C_MethodWeight {
            get {
                return ResourceManager.GetString("C_MethodWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部记录.
        /// </summary>
        public static string C_ModeOverview {
            get {
                return ResourceManager.GetString("C_ModeOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按时间查看.
        /// </summary>
        public static string C_ModeRecords {
            get {
                return ResourceManager.GetString("C_ModeRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无历史记录.
        /// </summary>
        public static string C_NoData {
            get {
                return ResourceManager.GetString("C_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string C_Refresh {
            get {
                return ResourceManager.GetString("C_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择班级.
        /// </summary>
        public static string C_SelectClass {
            get {
                return ResourceManager.GetString("C_SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看模式.
        /// </summary>
        public static string C_SelectMode {
            get {
                return ResourceManager.GetString("C_SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择奖池.
        /// </summary>
        public static string C_SelectPool {
            get {
                return ResourceManager.GetString("C_SelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名模式.
        /// </summary>
        public static string H_DrawMode {
            get {
                return ResourceManager.GetString("H_DrawMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名人数.
        /// </summary>
        public static string H_DrawNumbers {
            get {
                return ResourceManager.GetString("H_DrawNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名时间.
        /// </summary>
        public static string H_DrawTime {
            get {
                return ResourceManager.GetString("H_DrawTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string H_Gender {
            get {
                return ResourceManager.GetString("H_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别限制.
        /// </summary>
        public static string H_GenderLimit {
            get {
                return ResourceManager.GetString("H_GenderLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小组.
        /// </summary>
        public static string H_Group {
            get {
                return ResourceManager.GetString("H_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小组限制.
        /// </summary>
        public static string H_GroupLimit {
            get {
                return ResourceManager.GetString("H_GroupLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取数量.
        /// </summary>
        public static string H_LotteryNumbers {
            get {
                return ResourceManager.GetString("H_LotteryNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖时间.
        /// </summary>
        public static string H_LotteryTime {
            get {
                return ResourceManager.GetString("H_LotteryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string H_Name {
            get {
                return ResourceManager.GetString("H_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string H_PrizeName {
            get {
                return ResourceManager.GetString("H_PrizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string H_Serial {
            get {
                return ResourceManager.GetString("H_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学号.
        /// </summary>
        public static string H_StudentId {
            get {
                return ResourceManager.GetString("H_StudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目.
        /// </summary>
        public static string H_Subject {
            get {
                return ResourceManager.GetString("H_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中奖次数.
        /// </summary>
        public static string H_TotalCountLottery {
            get {
                return ResourceManager.GetString("H_TotalCountLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名次数.
        /// </summary>
        public static string H_TotalCountRollCall {
            get {
                return ResourceManager.GetString("H_TotalCountRollCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重.
        /// </summary>
        public static string H_Weight {
            get {
                return ResourceManager.GetString("H_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖历史.
        /// </summary>
        public static string Tab_Lottery {
            get {
                return ResourceManager.GetString("Tab_Lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名历史.
        /// </summary>
        public static string Tab_RollCall {
            get {
                return ResourceManager.GetString("Tab_RollCall", resourceCulture);
            }
        }
    }
}
