//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Linkage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Linkage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string C_Confirm {
            get {
                return ResourceManager.GetString("C_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除课程表.
        /// </summary>
        public static string C_CsesClear {
            get {
                return ResourceManager.GetString("C_CsesClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入课程表.
        /// </summary>
        public static string C_CsesImport {
            get {
                return ResourceManager.GetString("C_CsesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看摘要.
        /// </summary>
        public static string C_CsesView {
            get {
                return ResourceManager.GetString("C_CsesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要清除当前导入的 CSES 课程表吗？.
        /// </summary>
        public static string M_CsesClearContent {
            get {
                return ResourceManager.GetString("M_CsesClearContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已清除 CSES 课程表。.
        /// </summary>
        public static string M_CsesCleared {
            get {
                return ResourceManager.GetString("M_CsesCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除课程表.
        /// </summary>
        public static string M_CsesClearTitle {
            get {
                return ResourceManager.GetString("M_CsesClearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已导入 CSES 课程表：{0}.
        /// </summary>
        public static string M_CsesImported {
            get {
                return ResourceManager.GetString("M_CsesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未导入有效的 CSES 课程表。.
        /// </summary>
        public static string M_CsesMissing {
            get {
                return ResourceManager.GetString("M_CsesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课间.
        /// </summary>
        public static string O_BreakAssignment_Break {
            get {
                return ResourceManager.GetString("O_BreakAssignment_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下节课.
        /// </summary>
        public static string O_BreakAssignment_NextClass {
            get {
                return ResourceManager.GetString("O_BreakAssignment_NextClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上节课.
        /// </summary>
        public static string O_BreakAssignment_PreviousClass {
            get {
                return ResourceManager.GetString("O_BreakAssignment_PreviousClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIsland.
        /// </summary>
        public static string O_DataSource_ClassIsland {
            get {
                return ResourceManager.GetString("O_DataSource_ClassIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSES 课程表.
        /// </summary>
        public static string O_DataSource_Cses {
            get {
                return ResourceManager.GetString("O_DataSource_Cses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string O_DataSource_Off {
            get {
                return ResourceManager.GetString("O_DataSource_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联动设置.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课前课后.
        /// </summary>
        public static string S_ClassTime {
            get {
                return ResourceManager.GetString("S_ClassTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下课隐藏悬浮窗.
        /// </summary>
        public static string S_ClassTime_HideFloatingWindow {
            get {
                return ResourceManager.GetString("S_ClassTime_HideFloatingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程结束时自动隐藏悬浮窗。.
        /// </summary>
        public static string S_ClassTime_HideFloatingWindow_D {
            get {
                return ResourceManager.GetString("S_ClassTime_HideFloatingWindow_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课后禁用延迟.
        /// </summary>
        public static string S_ClassTime_PostClassDisableDelay {
            get {
                return ResourceManager.GetString("S_ClassTime_PostClassDisableDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程结束后延迟多少秒禁用相关抽取入口。.
        /// </summary>
        public static string S_ClassTime_PostClassDisableDelay_D {
            get {
                return ResourceManager.GetString("S_ClassTime_PostClassDisableDelay_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课前解禁时间.
        /// </summary>
        public static string S_ClassTime_PreClassEnableTime {
            get {
                return ResourceManager.GetString("S_ClassTime_PreClassEnableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上课前多少秒提前解除课间禁用。.
        /// </summary>
        public static string S_ClassTime_PreClassEnableTime_D {
            get {
                return ResourceManager.GetString("S_ClassTime_PreClassEnableTime_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课前重置.
        /// </summary>
        public static string S_ClassTime_PreClassReset {
            get {
                return ResourceManager.GetString("S_ClassTime_PreClassReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上课前自动重置临时抽取记录。.
        /// </summary>
        public static string S_ClassTime_PreClassReset_D {
            get {
                return ResourceManager.GetString("S_ClassTime_PreClassReset_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课前重置时间.
        /// </summary>
        public static string S_ClassTime_PreClassResetTime {
            get {
                return ResourceManager.GetString("S_ClassTime_PreClassResetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 距离上课多少秒内执行课前重置。.
        /// </summary>
        public static string S_ClassTime_PreClassResetTime_D {
            get {
                return ResourceManager.GetString("S_ClassTime_PreClassResetTime_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSES 课程表.
        /// </summary>
        public static string S_Cses {
            get {
                return ResourceManager.GetString("S_Cses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程联动.
        /// </summary>
        public static string S_External {
            get {
                return ResourceManager.GetString("S_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据源.
        /// </summary>
        public static string S_External_DataSource {
            get {
                return ResourceManager.GetString("S_External_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择课程或外部联动数据来源。.
        /// </summary>
        public static string S_External_DataSource_D {
            get {
                return ResourceManager.GetString("S_External_DataSource_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限制非上课时段操作.
        /// </summary>
        public static string S_External_InstantDrawDisable {
            get {
                return ResourceManager.GetString("S_External_InstantDrawDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程数据源明确显示处于课间或非上课时段时，限制抽取和重置。关闭后不作限制。.
        /// </summary>
        public static string S_External_InstantDrawDisable_D {
            get {
                return ResourceManager.GetString("S_External_InstantDrawDisable_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许验证后继续.
        /// </summary>
        public static string S_External_VerificationRequired {
            get {
                return ResourceManager.GetString("S_External_VerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅在已启用非上课时段限制时生效。开启后，通过已配置的安全验证可以临时继续抽取或重置；关闭后将直接阻止。.
        /// </summary>
        public static string S_External_VerificationRequired_D {
            get {
                return ResourceManager.GetString("S_External_VerificationRequired_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目历史记录.
        /// </summary>
        public static string S_SubjectHistory {
            get {
                return ResourceManager.GetString("S_SubjectHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课间归属.
        /// </summary>
        public static string S_SubjectHistory_BreakAssignment {
            get {
                return ResourceManager.GetString("S_SubjectHistory_BreakAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择课间时段的历史记录归属方式。.
        /// </summary>
        public static string S_SubjectHistory_BreakAssignment_D {
            get {
                return ResourceManager.GetString("S_SubjectHistory_BreakAssignment_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目历史记录过滤.
        /// </summary>
        public static string S_SubjectHistory_Filter {
            get {
                return ResourceManager.GetString("S_SubjectHistory_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算权重时只使用当前科目的历史记录。.
        /// </summary>
        public static string S_SubjectHistory_Filter_D {
            get {
                return ResourceManager.GetString("S_SubjectHistory_Filter_D", resourceCulture);
            }
        }
    }
}
