//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Security {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Security.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 安全设置.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 保护范围.
        /// </summary>
        public static string S_Protection {
            get {
                return ResourceManager.GetString("S_Protection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 联动操作前验证.
        /// </summary>
        public static string S_Protection_LinkageOperations {
            get {
                return ResourceManager.GetString("S_Protection_LinkageOperations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 外部联动触发抽取或页面切换前要求验证。.
        /// </summary>
        public static string S_Protection_LinkageOperations_D {
            get {
                return ResourceManager.GetString("S_Protection_LinkageOperations_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 敏感操作前验证.
        /// </summary>
        public static string S_Protection_SensitiveOperations {
            get {
                return ResourceManager.GetString("S_Protection_SensitiveOperations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 修改安全、联动、名单等关键设置前要求验证。.
        /// </summary>
        public static string S_Protection_SensitiveOperations_D {
            get {
                return ResourceManager.GetString("S_Protection_SensitiveOperations_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 验证方式.
        /// </summary>
        public static string S_Verification {
            get {
                return ResourceManager.GetString("S_Verification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用密码验证.
        /// </summary>
        public static string S_Verification_Password {
            get {
                return ResourceManager.GetString("S_Verification_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 使用本地密码保护敏感操作。.
        /// </summary>
        public static string S_Verification_Password_D {
            get {
                return ResourceManager.GetString("S_Verification_Password_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用 TOTP 验证.
        /// </summary>
        public static string S_Verification_Totp {
            get {
                return ResourceManager.GetString("S_Verification_Totp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 使用一次性验证码保护敏感操作。.
        /// </summary>
        public static string S_Verification_Totp_D {
            get {
                return ResourceManager.GetString("S_Verification_Totp_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用 USB 绑定.
        /// </summary>
        public static string S_Verification_UsbBinding {
            get {
                return ResourceManager.GetString("S_Verification_UsbBinding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 仅在绑定设备存在时允许通过验证。.
        /// </summary>
        public static string S_Verification_UsbBinding_D {
            get {
                return ResourceManager.GetString("S_Verification_UsbBinding_D", resourceCulture);
            }
        }
    }
}
