//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.AttachedSettings {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.AttachedSettings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 概率.
        /// </summary>
        public static string C_Probability {
            get {
                return ResourceManager.GetString("C_Probability", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 默认值为 0，权重范围为 0-100；0 为不参与，100 为必中。.
        /// </summary>
        public static string C_ProbabilityDescription {
            get {
                return ResourceManager.GetString("C_ProbabilityDescription", resourceCulture);
            }
        }

        public static string C_SpecificVoice {
            get {
                return ResourceManager.GetString("C_SpecificVoice", resourceCulture);
            }
        }

        public static string C_SpecificVoiceAlias {
            get {
                return ResourceManager.GetString("C_SpecificVoiceAlias", resourceCulture);
            }
        }

        public static string C_SpecificVoiceAliasPlaceholder {
            get {
                return ResourceManager.GetString("C_SpecificVoiceAliasPlaceholder", resourceCulture);
            }
        }

        public static string C_SpecificVoicePrefix {
            get {
                return ResourceManager.GetString("C_SpecificVoicePrefix", resourceCulture);
            }
        }

        public static string C_SpecificVoiceSuffix {
            get {
                return ResourceManager.GetString("C_SpecificVoiceSuffix", resourceCulture);
            }
        }

        public static string C_SpecificVoiceOptional {
            get {
                return ResourceManager.GetString("C_SpecificVoiceOptional", resourceCulture);
            }
        }

        public static string C_SpecificVoiceDescription {
            get {
                return ResourceManager.GetString("C_SpecificVoiceDescription", resourceCulture);
            }
        }
    }
}
