//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.FloatingWindow {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.FloatingWindow.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 不置顶.
        /// </summary>
        public static string O_TopmostMode_None {
            get {
                return ResourceManager.GetString("O_TopmostMode_None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string O_TopmostMode_Topmost {
            get {
                return ResourceManager.GetString("O_TopmostMode_Topmost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UIAccess 置顶.
        /// </summary>
        public static string O_TopmostMode_UIAccess {
            get {
                return ResourceManager.GetString("O_TopmostMode_UIAccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 悬浮窗管理.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 按钮.
        /// </summary>
        public static string S_Buttons {
            get {
                return ResourceManager.GetString("S_Buttons", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽奖按钮.
        /// </summary>
        public static string S_Buttons_Lottery {
            get {
                return ResourceManager.GetString("S_Buttons_Lottery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在悬浮窗中显示抽奖入口。.
        /// </summary>
        public static string S_Buttons_Lottery_D {
            get {
                return ResourceManager.GetString("S_Buttons_Lottery_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 闪抽按钮.
        /// </summary>
        public static string S_Buttons_QuickDraw {
            get {
                return ResourceManager.GetString("S_Buttons_QuickDraw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在悬浮窗中显示快速抽取入口。.
        /// </summary>
        public static string S_Buttons_QuickDraw_D {
            get {
                return ResourceManager.GetString("S_Buttons_QuickDraw_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点名按钮.
        /// </summary>
        public static string S_Buttons_RollCall {
            get {
                return ResourceManager.GetString("S_Buttons_RollCall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在悬浮窗中显示点名入口。.
        /// </summary>
        public static string S_Buttons_RollCall_D {
            get {
                return ResourceManager.GetString("S_Buttons_RollCall_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示与行为.
        /// </summary>
        public static string S_Display {
            get {
                return ResourceManager.GetString("S_Display", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 贴边收纳.
        /// </summary>
        public static string S_Dock {
            get {
                return ResourceManager.GetString("S_Dock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 收纳手柄尺寸.
        /// </summary>
        public static string S_Dock_Size {
            get {
                return ResourceManager.GetString("S_Dock_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 调整贴边收纳后边缘手柄的正方形边长。.
        /// </summary>
        public static string S_Dock_Size_D {
            get {
                return ResourceManager.GetString("S_Dock_Size_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 悬浮窗透明度.
        /// </summary>
        public static string S_Display_Opacity {
            get {
                return ResourceManager.GetString("S_Display_Opacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置悬浮窗整体不透明度。.
        /// </summary>
        public static string S_Display_Opacity_D {
            get {
                return ResourceManager.GetString("S_Display_Opacity_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启动时显示悬浮窗.
        /// </summary>
        public static string S_Display_StartupDisplay {
            get {
                return ResourceManager.GetString("S_Display_StartupDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控制程序启动后是否自动打开悬浮窗。.
        /// </summary>
        public static string S_Display_StartupDisplay_D {
            get {
                return ResourceManager.GetString("S_Display_StartupDisplay_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 悬浮窗置顶模式.
        /// </summary>
        public static string S_Display_TopmostMode {
            get {
                return ResourceManager.GetString("S_Display_TopmostMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择悬浮窗是否保持在其他窗口上方。.
        /// </summary>
        public static string S_Display_TopmostMode_D {
            get {
                return ResourceManager.GetString("S_Display_TopmostMode_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择悬浮窗置顶方式，UIAccess 会在重启时请求管理员权限，取消或失败时本次启动使用普通置顶.
        /// </summary>
        public static string S_Display_TopmostMode_Windows_D {
            get {
                return ResourceManager.GetString("S_Display_TopmostMode_Windows_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 交互.
        /// </summary>
        public static string S_Interaction {
            get {
                return ResourceManager.GetString("S_Interaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 不抢占焦点.
        /// </summary>
        public static string S_Interaction_DoNotStealFocus {
            get {
                return ResourceManager.GetString("S_Interaction_DoNotStealFocus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点击悬浮窗时尽量不打断当前窗口输入。.
        /// </summary>
        public static string S_Interaction_DoNotStealFocus_D {
            get {
                return ResourceManager.GetString("S_Interaction_DoNotStealFocus_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 可拖动.
        /// </summary>
        public static string S_Interaction_Draggable {
            get {
                return ResourceManager.GetString("S_Interaction_Draggable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 允许拖动悬浮窗位置。.
        /// </summary>
        public static string S_Interaction_Draggable_D {
            get {
                return ResourceManager.GetString("S_Interaction_Draggable_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 前台窗口匹配时隐藏.
        /// </summary>
        public static string S_Interaction_HideOnForeground {
            get {
                return ResourceManager.GetString("S_Interaction_HideOnForeground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 当前窗口命中规则时自动隐藏悬浮窗。.
        /// </summary>
        public static string S_Interaction_HideOnForeground_D {
            get {
                return ResourceManager.GetString("S_Interaction_HideOnForeground_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 隐藏进程名规则.
        /// </summary>
        public static string S_Interaction_HideOnForegroundProcessNames {
            get {
                return ResourceManager.GetString("S_Interaction_HideOnForegroundProcessNames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用于匹配前台进程名的规则列表。.
        /// </summary>
        public static string S_Interaction_HideOnForegroundProcessNames_D {
            get {
                return ResourceManager.GetString("S_Interaction_HideOnForegroundProcessNames_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 隐藏窗口标题规则.
        /// </summary>
        public static string S_Interaction_HideOnForegroundWindowTitles {
            get {
                return ResourceManager.GetString("S_Interaction_HideOnForegroundWindowTitles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用于匹配前台窗口标题的规则列表。.
        /// </summary>
        public static string S_Interaction_HideOnForegroundWindowTitles_D {
            get {
                return ResourceManager.GetString("S_Interaction_HideOnForegroundWindowTitles_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 长按判定时间.
        /// </summary>
        public static string S_Interaction_LongPressDuration {
            get {
                return ResourceManager.GetString("S_Interaction_LongPressDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 触发长按操作需要持续的毫秒数。.
        /// </summary>
        public static string S_Interaction_LongPressDuration_D {
            get {
                return ResourceManager.GetString("S_Interaction_LongPressDuration_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 吸附屏幕边缘.
        /// </summary>
        public static string S_Interaction_StickToEdge {
            get {
                return ResourceManager.GetString("S_Interaction_StickToEdge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 拖动结束后自动贴近屏幕边缘。.
        /// </summary>
        public static string S_Interaction_StickToEdge_D {
            get {
                return ResourceManager.GetString("S_Interaction_StickToEdge_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 吸附恢复时间.
        /// </summary>
        public static string S_Interaction_StickToEdgeRecoverSeconds {
            get {
                return ResourceManager.GetString("S_Interaction_StickToEdgeRecoverSeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 悬浮窗贴边后恢复显示所需的秒数。.
        /// </summary>
        public static string S_Interaction_StickToEdgeRecoverSeconds_D {
            get {
                return ResourceManager.GetString("S_Interaction_StickToEdgeRecoverSeconds_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 悬浮窗控件.
        /// </summary>
        public static string S_Buttons_EnabledItems {
            get {
                return ResourceManager.GetString("S_Buttons_EnabledItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择悬浮窗中显示的入口和扩展控件。.
        /// </summary>
        public static string S_Buttons_EnabledItems_D {
            get {
                return ResourceManager.GetString("S_Buttons_EnabledItems_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控件排列.
        /// </summary>
        public static string S_Buttons_Placement {
            get {
                return ResourceManager.GetString("S_Buttons_Placement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择悬浮窗按钮的排列方式。.
        /// </summary>
        public static string S_Buttons_Placement_D {
            get {
                return ResourceManager.GetString("S_Buttons_Placement_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 矩形.
        /// </summary>
        public static string O_Placement_Rectangle {
            get {
                return ResourceManager.GetString("O_Placement_Rectangle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 纵向.
        /// </summary>
        public static string O_Placement_Vertical {
            get {
                return ResourceManager.GetString("O_Placement_Vertical", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 横向.
        /// </summary>
        public static string O_Placement_Horizontal {
            get {
                return ResourceManager.GetString("O_Placement_Horizontal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控件显示样式.
        /// </summary>
        public static string S_Buttons_DisplayStyle {
            get {
                return ResourceManager.GetString("S_Buttons_DisplayStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择悬浮窗控件显示图标、文字或二者同时显示。.
        /// </summary>
        public static string S_Buttons_DisplayStyle_D {
            get {
                return ResourceManager.GetString("S_Buttons_DisplayStyle_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 图标和文字.
        /// </summary>
        public static string O_DisplayStyle_IconText {
            get {
                return ResourceManager.GetString("O_DisplayStyle_IconText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 仅图标.
        /// </summary>
        public static string O_DisplayStyle_Icon {
            get {
                return ResourceManager.GetString("O_DisplayStyle_Icon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 仅文字.
        /// </summary>
        public static string O_DisplayStyle_Text {
            get {
                return ResourceManager.GetString("O_DisplayStyle_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控件尺寸.
        /// </summary>
        public static string S_Buttons_Size {
            get {
                return ResourceManager.GetString("S_Buttons_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 调整悬浮窗控件的整体尺寸。.
        /// </summary>
        public static string S_Buttons_Size_D {
            get {
                return ResourceManager.GetString("S_Buttons_Size_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 极小.
        /// </summary>
        public static string O_Size_XXS {
            get {
                return ResourceManager.GetString("O_Size_XXS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 很小.
        /// </summary>
        public static string O_Size_XS {
            get {
                return ResourceManager.GetString("O_Size_XS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 小.
        /// </summary>
        public static string O_Size_S {
            get {
                return ResourceManager.GetString("O_Size_S", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 中.
        /// </summary>
        public static string O_Size_M {
            get {
                return ResourceManager.GetString("O_Size_M", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 大.
        /// </summary>
        public static string O_Size_L {
            get {
                return ResourceManager.GetString("O_Size_L", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 很大.
        /// </summary>
        public static string O_Size_XL {
            get {
                return ResourceManager.GetString("O_Size_XL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 极大.
        /// </summary>
        public static string O_Size_XXL {
            get {
                return ResourceManager.GetString("O_Size_XXL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 贴边显示样式.
        /// </summary>
        public static string S_Interaction_StickToEdgeDisplayStyle {
            get {
                return ResourceManager.GetString("S_Interaction_StickToEdgeDisplayStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择悬浮窗贴边收纳后的显示方式。.
        /// </summary>
        public static string S_Interaction_StickToEdgeDisplayStyle_D {
            get {
                return ResourceManager.GetString("S_Interaction_StickToEdgeDisplayStyle_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 图标.
        /// </summary>
        public static string O_StickDisplay_Icon {
            get {
                return ResourceManager.GetString("O_StickDisplay_Icon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 文字.
        /// </summary>
        public static string O_StickDisplay_Text {
            get {
                return ResourceManager.GetString("O_StickDisplay_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 箭头.
        /// </summary>
        public static string O_StickDisplay_Arrow {
            get {
                return ResourceManager.GetString("O_StickDisplay_Arrow", resourceCulture);
            }
        }
    }
}
