//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Personalized.Music {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Personalized.Music.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string C_Delete {
            get {
                return ResourceManager.GetString("C_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 曲目.
        /// </summary>
        public static string C_FileName {
            get {
                return ResourceManager.GetString("C_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式.
        /// </summary>
        public static string C_Format {
            get {
                return ResourceManager.GetString("C_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入音乐.
        /// </summary>
        public static string C_Import {
            get {
                return ResourceManager.GetString("C_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string C_Operations {
            get {
                return ResourceManager.GetString("C_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试听.
        /// </summary>
        public static string C_Preview {
            get {
                return ResourceManager.GetString("C_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大小.
        /// </summary>
        public static string C_Size {
            get {
                return ResourceManager.GetString("C_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        public static string C_Stop {
            get {
                return ResourceManager.GetString("C_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除“{0}”后，所有抽取设置中引用它的位置会重置为不开启音乐。.
        /// </summary>
        public static string M_DeleteContent {
            get {
                return ResourceManager.GetString("M_DeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法删除该音乐文件。.
        /// </summary>
        public static string M_DeleteFailed {
            get {
                return ResourceManager.GetString("M_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string M_DeletePrimary {
            get {
                return ResourceManager.GetString("M_DeletePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已删除“{0}”。.
        /// </summary>
        public static string M_DeleteSuccess {
            get {
                return ResourceManager.GetString("M_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除音乐.
        /// </summary>
        public static string M_DeleteTitle {
            get {
                return ResourceManager.GetString("M_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未导入音乐。.
        /// </summary>
        public static string M_Empty {
            get {
                return ResourceManager.GetString("M_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已导入 {0} 首音乐。.
        /// </summary>
        public static string M_Imported {
            get {
                return ResourceManager.GetString("M_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法导入所选音乐文件。.
        /// </summary>
        public static string M_ImportFailed {
            get {
                return ResourceManager.GetString("M_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法试听该音乐文件。.
        /// </summary>
        public static string M_PreviewFailed {
            get {
                return ResourceManager.GetString("M_PreviewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐库.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地音乐库.
        /// </summary>
        public static string S_Library {
            get {
                return ResourceManager.GetString("S_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入的音乐会复制到应用数据目录，可供所有抽取场景选择。.
        /// </summary>
        public static string S_Library_D {
            get {
                return ResourceManager.GetString("S_Library_D", resourceCulture);
            }
        }
    }
}
