//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.MainPages.RollCall {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.MainPages.RollCall.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string C_ListSettings => ResourceManager.GetString("C_ListSettings", resourceCulture);
        public static string C_Close => ResourceManager.GetString("C_Close", resourceCulture);
        public static string C_RemainingListTitle => ResourceManager.GetString("C_RemainingListTitle", resourceCulture);
        public static string C_Reset => ResourceManager.GetString("C_Reset", resourceCulture);
        public static string C_RollCallSettings => ResourceManager.GetString("C_RollCallSettings", resourceCulture);
        public static string C_ShowRemainingList => ResourceManager.GetString("C_ShowRemainingList", resourceCulture);
        public static string C_Start => ResourceManager.GetString("C_Start", resourceCulture);
        public static string C_Stop => ResourceManager.GetString("C_Stop", resourceCulture);
        public static string M_CountSummaryFormat => ResourceManager.GetString("M_CountSummaryFormat", resourceCulture);
        public static string M_DrawFailed => ResourceManager.GetString("M_DrawFailed", resourceCulture);
        public static string M_DrawnCountFormat => ResourceManager.GetString("M_DrawnCountFormat", resourceCulture);
        public static string M_InvalidWeight => ResourceManager.GetString("M_InvalidWeight", resourceCulture);
        public static string M_NoCandidates => ResourceManager.GetString("M_NoCandidates", resourceCulture);
        public static string M_NoEligibleCandidates => ResourceManager.GetString("M_NoEligibleCandidates", resourceCulture);
        public static string M_NoRemainingStudents => ResourceManager.GetString("M_NoRemainingStudents", resourceCulture);
        public static string M_NoStudents => ResourceManager.GetString("M_NoStudents", resourceCulture);
        public static string M_ResultSeparator => ResourceManager.GetString("M_ResultSeparator", resourceCulture);
        public static string M_Ready => ResourceManager.GetString("M_Ready", resourceCulture);
        public static string M_RepeatLimitExhausted => ResourceManager.GetString("M_RepeatLimitExhausted", resourceCulture);
        public static string M_ResetDone => ResourceManager.GetString("M_ResetDone", resourceCulture);
        public static string M_AutoResetDone => ResourceManager.GetString("M_AutoResetDone", resourceCulture);
        public static string O_AllGenders => ResourceManager.GetString("O_AllGenders", resourceCulture);
        public static string O_AllGroups => ResourceManager.GetString("O_AllGroups", resourceCulture);
    }
}
