//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagement.LotteryList {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagement.LotteryList.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        public static string C_InfoTitle {
            get {
                return ResourceManager.GetString("C_InfoTitle", resourceCulture);
            }
        }
        
        public static string C_InfoMessage {
            get {
                return ResourceManager.GetString("C_InfoMessage", resourceCulture);
            }
        }
        
        public static string C_CurrentList {
            get {
                return ResourceManager.GetString("C_CurrentList", resourceCulture);
            }
        }
        
        public static string C_CurrentList_D {
            get {
                return ResourceManager.GetString("C_CurrentList_D", resourceCulture);
            }
        }
        
        public static string C_Refresh {
            get {
                return ResourceManager.GetString("C_Refresh", resourceCulture);
            }
        }
        
        public static string C_ImportList {
            get {
                return ResourceManager.GetString("C_ImportList", resourceCulture);
            }
        }

        public static string C_ExportList {
            get {
                return ResourceManager.GetString("C_ExportList", resourceCulture);
            }
        }

        public static string C_AddPrize {
            get {
                return ResourceManager.GetString("C_AddPrize", resourceCulture);
            }
        }
        
        public static string C_AddList {
            get {
                return ResourceManager.GetString("C_AddList", resourceCulture);
            }
        }
        
        public static string C_RenameList {
            get {
                return ResourceManager.GetString("C_RenameList", resourceCulture);
            }
        }
        
        public static string C_DeleteList {
            get {
                return ResourceManager.GetString("C_DeleteList", resourceCulture);
            }
        }
        
        public static string C_Operations {
            get {
                return ResourceManager.GetString("C_Operations", resourceCulture);
            }
        }
        
        public static string C_DeletePrize {
            get {
                return ResourceManager.GetString("C_DeletePrize", resourceCulture);
            }
        }
        
        public static string C_Exists {
            get {
                return ResourceManager.GetString("C_Exists", resourceCulture);
            }
        }
        
        public static string C_PrizeId {
            get {
                return ResourceManager.GetString("C_PrizeId", resourceCulture);
            }
        }
        
        public static string C_Name {
            get {
                return ResourceManager.GetString("C_Name", resourceCulture);
            }
        }
        
        public static string C_Weight {
            get {
                return ResourceManager.GetString("C_Weight", resourceCulture);
            }
        }
        
        public static string C_Count {
            get {
                return ResourceManager.GetString("C_Count", resourceCulture);
            }
        }
        
        public static string C_Tags {
            get {
                return ResourceManager.GetString("C_Tags", resourceCulture);
            }
        }
        
        public static string C_ImportTitle {
            get {
                return ResourceManager.GetString("C_ImportTitle", resourceCulture);
            }
        }
        
        public static string C_TargetList {
            get {
                return ResourceManager.GetString("C_TargetList", resourceCulture);
            }
        }
        
        public static string C_SelectFile {
            get {
                return ResourceManager.GetString("C_SelectFile", resourceCulture);
            }
        }
        
        public static string C_NoFileSelected {
            get {
                return ResourceManager.GetString("C_NoFileSelected", resourceCulture);
            }
        }
        
        public static string C_SelectFileButton {
            get {
                return ResourceManager.GetString("C_SelectFileButton", resourceCulture);
            }
        }
        
        public static string C_SupportedFormats {
            get {
                return ResourceManager.GetString("C_SupportedFormats", resourceCulture);
            }
        }
        
        public static string C_ColumnMapping {
            get {
                return ResourceManager.GetString("C_ColumnMapping", resourceCulture);
            }
        }
        
        public static string C_ColumnMapping_D {
            get {
                return ResourceManager.GetString("C_ColumnMapping_D", resourceCulture);
            }
        }
        
        public static string C_PrizeIdColumn {
            get {
                return ResourceManager.GetString("C_PrizeIdColumn", resourceCulture);
            }
        }
        
        public static string C_NameColumn {
            get {
                return ResourceManager.GetString("C_NameColumn", resourceCulture);
            }
        }
        
        public static string C_WeightColumn {
            get {
                return ResourceManager.GetString("C_WeightColumn", resourceCulture);
            }
        }
        
        public static string C_CountColumn {
            get {
                return ResourceManager.GetString("C_CountColumn", resourceCulture);
            }
        }
        
        public static string C_TagsColumn {
            get {
                return ResourceManager.GetString("C_TagsColumn", resourceCulture);
            }
        }
        
        public static string C_NoneColumn {
            get {
                return ResourceManager.GetString("C_NoneColumn", resourceCulture);
            }
        }
        
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }

        public static string C_Edit {
            get {
                return ResourceManager.GetString("C_Edit", resourceCulture);
            }
        }
        
        public static string C_Import {
            get {
                return ResourceManager.GetString("C_Import", resourceCulture);
            }
        }
        
        public static string C_FilePickerTitle {
            get {
                return ResourceManager.GetString("C_FilePickerTitle", resourceCulture);
            }
        }
        
        public static string C_FilePickerTypeName {
            get {
                return ResourceManager.GetString("C_FilePickerTypeName", resourceCulture);
            }
        }
        
        public static string C_DefaultListName {
            get {
                return ResourceManager.GetString("C_DefaultListName", resourceCulture);
            }
        }
        
        public static string M_SelectFileFirst {
            get {
                return ResourceManager.GetString("M_SelectFileFirst", resourceCulture);
            }
        }
        
        public static string M_LoadFailed {
            get {
                return ResourceManager.GetString("M_LoadFailed", resourceCulture);
            }
        }
        
        public static string M_FileLoaded {
            get {
                return ResourceManager.GetString("M_FileLoaded", resourceCulture);
            }
        }
        
        public static string M_SelectRequiredColumns {
            get {
                return ResourceManager.GetString("M_SelectRequiredColumns", resourceCulture);
            }
        }
        
        public static string M_DuplicateTitle {
            get {
                return ResourceManager.GetString("M_DuplicateTitle", resourceCulture);
            }
        }
        
        public static string M_DuplicateContent {
            get {
                return ResourceManager.GetString("M_DuplicateContent", resourceCulture);
            }
        }
        
        public static string M_DuplicatePrimary {
            get {
                return ResourceManager.GetString("M_DuplicatePrimary", resourceCulture);
            }
        }
        
        public static string M_DuplicateSecondary {
            get {
                return ResourceManager.GetString("M_DuplicateSecondary", resourceCulture);
            }
        }
        
        public static string M_DuplicateClose {
            get {
                return ResourceManager.GetString("M_DuplicateClose", resourceCulture);
            }
        }
        
        public static string M_SelectListFirst {
            get {
                return ResourceManager.GetString("M_SelectListFirst", resourceCulture);
            }
        }
        
        public static string M_OverwriteTitle {
            get {
                return ResourceManager.GetString("M_OverwriteTitle", resourceCulture);
            }
        }
        
        public static string M_OverwriteContent {
            get {
                return ResourceManager.GetString("M_OverwriteContent", resourceCulture);
            }
        }
        
        public static string M_OverwritePrimary {
            get {
                return ResourceManager.GetString("M_OverwritePrimary", resourceCulture);
            }
        }
        
        public static string M_ImportSuccess {
            get {
                return ResourceManager.GetString("M_ImportSuccess", resourceCulture);
            }
        }
        
        public static string M_AddPrizeTitle {
            get {
                return ResourceManager.GetString("M_AddPrizeTitle", resourceCulture);
            }
        }
        
        public static string M_AddPrizeRequired {
            get {
                return ResourceManager.GetString("M_AddPrizeRequired", resourceCulture);
            }
        }
        
        public static string M_AddPrizeInvalidValues {
            get {
                return ResourceManager.GetString("M_AddPrizeInvalidValues", resourceCulture);
            }
        }
        
        public static string M_AddPrizeSuccess {
            get {
                return ResourceManager.GetString("M_AddPrizeSuccess", resourceCulture);
            }
        }
        
        public static string M_ListNameDialogTitle_Add {
            get {
                return ResourceManager.GetString("M_ListNameDialogTitle_Add", resourceCulture);
            }
        }
        
        public static string M_ListNameDialogTitle_Rename {
            get {
                return ResourceManager.GetString("M_ListNameDialogTitle_Rename", resourceCulture);
            }
        }
        
        public static string M_ListNameDialogPrimary_Add {
            get {
                return ResourceManager.GetString("M_ListNameDialogPrimary_Add", resourceCulture);
            }
        }
        
        public static string M_ListNameDialogPrimary_Rename {
            get {
                return ResourceManager.GetString("M_ListNameDialogPrimary_Rename", resourceCulture);
            }
        }
        
        public static string M_ListNamePlaceholder {
            get {
                return ResourceManager.GetString("M_ListNamePlaceholder", resourceCulture);
            }
        }
        
        public static string M_ListNameEmpty {
            get {
                return ResourceManager.GetString("M_ListNameEmpty", resourceCulture);
            }
        }
        
        public static string M_ListNameExists {
            get {
                return ResourceManager.GetString("M_ListNameExists", resourceCulture);
            }
        }
        
        public static string M_ListNameInvalid {
            get {
                return ResourceManager.GetString("M_ListNameInvalid", resourceCulture);
            }
        }
        
        public static string M_AddListSuccess {
            get {
                return ResourceManager.GetString("M_AddListSuccess", resourceCulture);
            }
        }
        
        public static string M_RenameListSuccess {
            get {
                return ResourceManager.GetString("M_RenameListSuccess", resourceCulture);
            }
        }
        
        public static string M_DeleteListTitle {
            get {
                return ResourceManager.GetString("M_DeleteListTitle", resourceCulture);
            }
        }
        
        public static string M_DeleteListContent {
            get {
                return ResourceManager.GetString("M_DeleteListContent", resourceCulture);
            }
        }
        
        public static string M_DeleteListPrimary {
            get {
                return ResourceManager.GetString("M_DeleteListPrimary", resourceCulture);
            }
        }
        
        public static string M_DeleteListSuccess {
            get {
                return ResourceManager.GetString("M_DeleteListSuccess", resourceCulture);
            }
        }
        
        public static string M_DeletePrizeTitle {
            get {
                return ResourceManager.GetString("M_DeletePrizeTitle", resourceCulture);
            }
        }
        
        public static string M_DeletePrizeContent {
            get {
                return ResourceManager.GetString("M_DeletePrizeContent", resourceCulture);
            }
        }
        
        public static string M_DeletePrizePrimary {
            get {
                return ResourceManager.GetString("M_DeletePrizePrimary", resourceCulture);
            }
        }
        
        public static string M_DeletePrizeSuccess {
            get {
                return ResourceManager.GetString("M_DeletePrizeSuccess", resourceCulture);
            }
        }
        
        public static string M_DeletePrizeNotFound {
            get {
                return ResourceManager.GetString("M_DeletePrizeNotFound", resourceCulture);
            }
        }
        
        public static string M_KeepOneList {
            get {
                return ResourceManager.GetString("M_KeepOneList", resourceCulture);
            }
        }
        
        public static string K_IdColumns {
            get {
                return ResourceManager.GetString("K_IdColumns", resourceCulture);
            }
        }
        
        public static string K_NameColumns {
            get {
                return ResourceManager.GetString("K_NameColumns", resourceCulture);
            }
        }
        
        public static string K_WeightColumns {
            get {
                return ResourceManager.GetString("K_WeightColumns", resourceCulture);
            }
        }
        
        public static string K_CountColumns {
            get {
                return ResourceManager.GetString("K_CountColumns", resourceCulture);
            }
        }
        
        public static string K_TagsColumns {
            get {
                return ResourceManager.GetString("K_TagsColumns", resourceCulture);
            }
        }
    }
}
