//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagement.RollCallList {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagement.RollCallList.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        public static string C_InfoTitle {
            get {
                return ResourceManager.GetString("C_InfoTitle", resourceCulture);
            }
        }
        
        public static string C_InfoMessage {
            get {
                return ResourceManager.GetString("C_InfoMessage", resourceCulture);
            }
        }
        
        public static string C_CurrentList {
            get {
                return ResourceManager.GetString("C_CurrentList", resourceCulture);
            }
        }
        
        public static string C_CurrentList_D {
            get {
                return ResourceManager.GetString("C_CurrentList_D", resourceCulture);
            }
        }
        
        public static string C_Refresh {
            get {
                return ResourceManager.GetString("C_Refresh", resourceCulture);
            }
        }
        
        public static string C_ImportList {
            get {
                return ResourceManager.GetString("C_ImportList", resourceCulture);
            }
        }

        public static string C_ExportList {
            get {
                return ResourceManager.GetString("C_ExportList", resourceCulture);
            }
        }

        public static string C_AddMember {
            get {
                return ResourceManager.GetString("C_AddMember", resourceCulture);
            }
        }
        
        public static string C_AddList {
            get {
                return ResourceManager.GetString("C_AddList", resourceCulture);
            }
        }
        
        public static string C_RenameList {
            get {
                return ResourceManager.GetString("C_RenameList", resourceCulture);
            }
        }
        
        public static string C_DeleteList {
            get {
                return ResourceManager.GetString("C_DeleteList", resourceCulture);
            }
        }
        
        public static string C_Operations {
            get {
                return ResourceManager.GetString("C_Operations", resourceCulture);
            }
        }
        
        public static string C_DeleteMember {
            get {
                return ResourceManager.GetString("C_DeleteMember", resourceCulture);
            }
        }
        
        public static string C_Exists {
            get {
                return ResourceManager.GetString("C_Exists", resourceCulture);
            }
        }
        
        public static string C_StudentId {
            get {
                return ResourceManager.GetString("C_StudentId", resourceCulture);
            }
        }
        
        public static string C_Name {
            get {
                return ResourceManager.GetString("C_Name", resourceCulture);
            }
        }
        
        public static string C_Gender {
            get {
                return ResourceManager.GetString("C_Gender", resourceCulture);
            }
        }
        
        public static string C_Group {
            get {
                return ResourceManager.GetString("C_Group", resourceCulture);
            }
        }
        
        public static string C_Tags {
            get {
                return ResourceManager.GetString("C_Tags", resourceCulture);
            }
        }
        
        public static string C_ImportTitle {
            get {
                return ResourceManager.GetString("C_ImportTitle", resourceCulture);
            }
        }
        
        public static string C_TargetList {
            get {
                return ResourceManager.GetString("C_TargetList", resourceCulture);
            }
        }
        
        public static string C_SelectFile {
            get {
                return ResourceManager.GetString("C_SelectFile", resourceCulture);
            }
        }
        
        public static string C_NoFileSelected {
            get {
                return ResourceManager.GetString("C_NoFileSelected", resourceCulture);
            }
        }
        
        public static string C_SelectFileButton {
            get {
                return ResourceManager.GetString("C_SelectFileButton", resourceCulture);
            }
        }
        
        public static string C_SupportedFormats {
            get {
                return ResourceManager.GetString("C_SupportedFormats", resourceCulture);
            }
        }
        
        public static string C_ColumnMapping {
            get {
                return ResourceManager.GetString("C_ColumnMapping", resourceCulture);
            }
        }
        
        public static string C_ColumnMapping_D {
            get {
                return ResourceManager.GetString("C_ColumnMapping_D", resourceCulture);
            }
        }
        
        public static string C_StudentIdColumn {
            get {
                return ResourceManager.GetString("C_StudentIdColumn", resourceCulture);
            }
        }
        
        public static string C_NameColumn {
            get {
                return ResourceManager.GetString("C_NameColumn", resourceCulture);
            }
        }
        
        public static string C_GenderColumn {
            get {
                return ResourceManager.GetString("C_GenderColumn", resourceCulture);
            }
        }
        
        public static string C_GroupColumn {
            get {
                return ResourceManager.GetString("C_GroupColumn", resourceCulture);
            }
        }
        
        public static string C_TagsColumn {
            get {
                return ResourceManager.GetString("C_TagsColumn", resourceCulture);
            }
        }
        
        public static string C_NoneColumn {
            get {
                return ResourceManager.GetString("C_NoneColumn", resourceCulture);
            }
        }
        
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }

        public static string C_Edit {
            get {
                return ResourceManager.GetString("C_Edit", resourceCulture);
            }
        }
        
        public static string C_Import {
            get {
                return ResourceManager.GetString("C_Import", resourceCulture);
            }
        }
        
        public static string C_FilePickerTitle {
            get {
                return ResourceManager.GetString("C_FilePickerTitle", resourceCulture);
            }
        }
        
        public static string C_FilePickerTypeName {
            get {
                return ResourceManager.GetString("C_FilePickerTypeName", resourceCulture);
            }
        }
        
        public static string C_DefaultListName {
            get {
                return ResourceManager.GetString("C_DefaultListName", resourceCulture);
            }
        }
        
        public static string M_SelectFileFirst {
            get {
                return ResourceManager.GetString("M_SelectFileFirst", resourceCulture);
            }
        }
        
        public static string M_LoadFailed {
            get {
                return ResourceManager.GetString("M_LoadFailed", resourceCulture);
            }
        }
        
        public static string M_FileLoaded {
            get {
                return ResourceManager.GetString("M_FileLoaded", resourceCulture);
            }
        }
        
        public static string M_SelectRequiredColumns {
            get {
                return ResourceManager.GetString("M_SelectRequiredColumns", resourceCulture);
            }
        }
        
        public static string M_DuplicateTitle {
            get {
                return ResourceManager.GetString("M_DuplicateTitle", resourceCulture);
            }
        }
        
        public static string M_DuplicateContent {
            get {
                return ResourceManager.GetString("M_DuplicateContent", resourceCulture);
            }
        }
        
        public static string M_DuplicatePrimary {
            get {
                return ResourceManager.GetString("M_DuplicatePrimary", resourceCulture);
            }
        }
        
        public static string M_DuplicateSecondary {
            get {
                return ResourceManager.GetString("M_DuplicateSecondary", resourceCulture);
            }
        }
        
        public static string M_DuplicateClose {
            get {
                return ResourceManager.GetString("M_DuplicateClose", resourceCulture);
            }
        }
        
        public static string M_SelectListFirst {
            get {
                return ResourceManager.GetString("M_SelectListFirst", resourceCulture);
            }
        }
        
        public static string M_OverwriteTitle {
            get {
                return ResourceManager.GetString("M_OverwriteTitle", resourceCulture);
            }
        }
        
        public static string M_OverwriteContent {
            get {
                return ResourceManager.GetString("M_OverwriteContent", resourceCulture);
            }
        }
        
        public static string M_OverwritePrimary {
            get {
                return ResourceManager.GetString("M_OverwritePrimary", resourceCulture);
            }
        }
        
        public static string M_ImportSuccess {
            get {
                return ResourceManager.GetString("M_ImportSuccess", resourceCulture);
            }
        }
        
        public static string M_AddMemberTitle {
            get {
                return ResourceManager.GetString("M_AddMemberTitle", resourceCulture);
            }
        }
        
        public static string M_AddMemberRequired {
            get {
                return ResourceManager.GetString("M_AddMemberRequired", resourceCulture);
            }
        }
        
        public static string M_AddMemberSuccess {
            get {
                return ResourceManager.GetString("M_AddMemberSuccess", resourceCulture);
            }
        }

        public static string M_AddMemberHistoryResetTitle {
            get {
                return ResourceManager.GetString("M_AddMemberHistoryResetTitle", resourceCulture);
            }
        }

        public static string M_AddMemberHistoryResetContent {
            get {
                return ResourceManager.GetString("M_AddMemberHistoryResetContent", resourceCulture);
            }
        }

        public static string M_AddMemberHistoryResetPrimary {
            get {
                return ResourceManager.GetString("M_AddMemberHistoryResetPrimary", resourceCulture);
            }
        }

        public static string M_AddMemberHistoryResetSecondary {
            get {
                return ResourceManager.GetString("M_AddMemberHistoryResetSecondary", resourceCulture);
            }
        }
        
        public static string M_ListNameDialogTitle_Add {
            get {
                return ResourceManager.GetString("M_ListNameDialogTitle_Add", resourceCulture);
            }
        }
        
        public static string M_ListNameDialogTitle_Rename {
            get {
                return ResourceManager.GetString("M_ListNameDialogTitle_Rename", resourceCulture);
            }
        }
        
        public static string M_ListNameDialogPrimary_Add {
            get {
                return ResourceManager.GetString("M_ListNameDialogPrimary_Add", resourceCulture);
            }
        }
        
        public static string M_ListNameDialogPrimary_Rename {
            get {
                return ResourceManager.GetString("M_ListNameDialogPrimary_Rename", resourceCulture);
            }
        }
        
        public static string M_ListNamePlaceholder {
            get {
                return ResourceManager.GetString("M_ListNamePlaceholder", resourceCulture);
            }
        }
        
        public static string M_ListNameEmpty {
            get {
                return ResourceManager.GetString("M_ListNameEmpty", resourceCulture);
            }
        }
        
        public static string M_ListNameExists {
            get {
                return ResourceManager.GetString("M_ListNameExists", resourceCulture);
            }
        }
        
        public static string M_ListNameInvalid {
            get {
                return ResourceManager.GetString("M_ListNameInvalid", resourceCulture);
            }
        }
        
        public static string M_AddListSuccess {
            get {
                return ResourceManager.GetString("M_AddListSuccess", resourceCulture);
            }
        }
        
        public static string M_RenameListSuccess {
            get {
                return ResourceManager.GetString("M_RenameListSuccess", resourceCulture);
            }
        }
        
        public static string M_DeleteListTitle {
            get {
                return ResourceManager.GetString("M_DeleteListTitle", resourceCulture);
            }
        }
        
        public static string M_DeleteListContent {
            get {
                return ResourceManager.GetString("M_DeleteListContent", resourceCulture);
            }
        }
        
        public static string M_DeleteListPrimary {
            get {
                return ResourceManager.GetString("M_DeleteListPrimary", resourceCulture);
            }
        }
        
        public static string M_DeleteListSuccess {
            get {
                return ResourceManager.GetString("M_DeleteListSuccess", resourceCulture);
            }
        }
        
        public static string M_DeleteMemberTitle {
            get {
                return ResourceManager.GetString("M_DeleteMemberTitle", resourceCulture);
            }
        }
        
        public static string M_DeleteMemberContent {
            get {
                return ResourceManager.GetString("M_DeleteMemberContent", resourceCulture);
            }
        }
        
        public static string M_DeleteMemberPrimary {
            get {
                return ResourceManager.GetString("M_DeleteMemberPrimary", resourceCulture);
            }
        }
        
        public static string M_DeleteMemberSuccess {
            get {
                return ResourceManager.GetString("M_DeleteMemberSuccess", resourceCulture);
            }
        }
        
        public static string M_DeleteMemberNotFound {
            get {
                return ResourceManager.GetString("M_DeleteMemberNotFound", resourceCulture);
            }
        }
        
        public static string M_KeepOneList {
            get {
                return ResourceManager.GetString("M_KeepOneList", resourceCulture);
            }
        }
        
        public static string K_IdColumns {
            get {
                return ResourceManager.GetString("K_IdColumns", resourceCulture);
            }
        }
        
        public static string K_NameColumns {
            get {
                return ResourceManager.GetString("K_NameColumns", resourceCulture);
            }
        }
        
        public static string K_GenderColumns {
            get {
                return ResourceManager.GetString("K_GenderColumns", resourceCulture);
            }
        }
        
        public static string K_GroupColumns {
            get {
                return ResourceManager.GetString("K_GroupColumns", resourceCulture);
            }
        }
        
        public static string K_TagsColumns {
            get {
                return ResourceManager.GetString("K_TagsColumns", resourceCulture);
            }
        }
    }
}
